const i18n = {
  messages: {
    fr: {
      'OpenEx - Crisis management exercises platform':
        'OpenEx - Plateforme d’exercices de crise',
      'Email address': 'Adresse email',
      Password: 'Mot de passe',
      'Sign in': "S'identifier",
      Dashboard: 'Tableau de bord',
      Exercises: 'Exercices',
      Players: 'Joueurs',
      Organizations: 'Organisations',
      Documents: 'Documents',
      Integrations: 'Intégrations',
      Settings: 'Paramètres',
      Profile: 'Profil',
      Logout: 'Se déconnecter',
      Firstname: 'Prénom',
      Lastname: 'Nom de famille',
      Organization: 'Organisation',
      Language: 'Langue',
      Injects: 'Stimulis',
      Messages: 'Messages',
      'Recent exercises': 'Exercices récents',
      'Next injects to send': 'Prochains stimlis à envoyer',
      'Organizations distribution across exercises':
        'Distribution des organisations dans les exercices',
      'Players distribution': 'Distribution des joueurs',
      Name: 'Nom',
      Subtitle: 'Sous-titre',
      'Start date': 'Date de début',
      'End date': 'Date de fin',
      Tags: 'Tags',
      'Create a new exercise': 'Créer un nouvel exercice',
      'Do you want to delete this player?':
        'Souhaitez-vous supprimer ce joueur ?',
      'Start date (optional)': 'Date de début (optionnel)',
      'Create a new player': 'Créer un nouveau joueur',
      'Update the player': 'Modifier le joueur',
      'one month': 'un mois',
      'Phone number (mobile)': 'Numéro de téléphone (mobile)',
      'Phone number (fix)': 'Numéro de téléphone (fixe)',
      'PGP public key': 'Clé publique PGP',
      'Create a new organization': 'Créer une nouvelle organisation',
      'Update the organization': "Modifier l'organisation",
      'Do you want to delete this organization?':
        'Souhaitez-vous supprimer cette organisation ?',
      Manual: 'Manuel',
      Parameters: 'Paramètres',
      'Default theme': 'Thème par défaut',
      'Default language': 'Langue par défaut',
      'Create a user': 'Créer un utilisateur',
      Administrator: 'Administrateur',
      Automatic: 'Automatique',
      'Passwords do no match': 'Les mots de passe ne correspondent pas',
      'Update the user password': "Modifier le mot de passe de l'utilisateur",
      'Update password': 'Modifier le mot de passe',
      Users: 'Utilisateurs',
      Groups: 'Groupes',
      'Create a new group': 'Créer un groupe',
      'Create a new tag': 'Créer un nouveau tag',
      'Do you want to delete this tag?': 'Souhaitez-vous supprimer ce tag ?',
      'Update the tag': 'Modifier le tag',
      'Manage grants': 'Gérer les permissions',
      'Manage users': 'Gérer les utilisateurs',
      'Do you want to delete this user?':
        'Souhaitez-vous supprimer cet utilisateur ?',
      'Do you want to delete this group?':
        'Souhaitez-vous supprimer ce groupe ?',
      'No tag': 'Aucun tag',
      'Update the user': "Modifier l'utilisateur",
      Exercise: 'Exercice',
      'Read/Write': 'Lecture/Ecriture',
      'Read Only': 'Lecture Seule',
      'Update the group': 'Modifier le groupe',
      Value: 'Valeur',
      Color: 'Couleur',
      Cancel: 'Annuler',
      Next: 'Suivant',
      Create: 'Créer',
      Launch: 'Lancer',
      Update: 'Modifier',
      Delete: 'Supprimer',
      Confirmation: 'Confirmation',
      Search: 'Rechercher',
      Required: 'Obligatoire',
      'Platform name': 'Nom de la plateforme',
      'Components version': 'Version des composants',
      Dark: 'Sombre',
      Light: 'Clair',
      'This field is required.': 'Ce champ est requis.',
      'The element has been updated': "L'élément a été modifié.",
      'The element already exists': "L'élément existe déjà.",
      'Manage the users of this group': 'Gérer les utilisateurs de ce groupe',
      'Create a new document': 'Créer un nouveau document',
      Close: 'Fermer',
      'Export to XLS': 'Exporter en XLS',
      Copy: 'Copier',
      Start: 'Démarrer',
      Status: 'Statut',
      Information: 'Information',
      Control: 'Contrôle',
      Scheduled: 'Planifié',
      Execution: 'Exécution',
      Dryrun: 'Simulation',
      Comcheck: 'Vérification',
      Send: 'Envoyer',
      Remove: 'Retirer',
      Add: 'Ajouter',
      Scenario: 'Scénario',
      Title: 'Titre',
      Enabled: 'Activé',
      Disabled: 'Désactivé',
      'Add target audiences in this inject': 'Ajouter des audiences cibles dans ce stimuli',
      'Targeted audiences': 'Audiences ciblées',
      'All audiences': 'Toutes les audiences',
      'Add target audiences': 'Ajouter des audiences cibles',
      'Trigger after': 'Se déclenche après',
      'Create a new inject': 'Créer un nouveau stimuli',
      'Remove from the audience': "Retirer de l'audience",
      'Update the audience': "Modifier l'audience",
      'Update the inject': 'Modifier le stimuli',
      'Do you want to remove the player from the audience?':
        'Souhaitez-vous retirer le joueur de cette audience ?',
      'Add players in this audience': 'Ajouter des joueurs dans cette audience',
      'Create a new audience': 'Créer une nouvelle audience',
      'Before starting the exercise, you can launch a comcheck to validate player email addresses and trigger a dryrun to send injects to the animation team.':
        "Avant de démarrer l'exercice, vous pouvez lancer une vérification pour valider les adresses emails des joueurs et une simulation pour envoyer les stimulis à l'équipe d'animation.",
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_manual: 'Manuel (rappel)',
      subject: 'Sujet du mail',
      body: 'Corps du mail',
      encrypted: 'Chiffrer ce mail',
    },
    en: {
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_manual: 'Manual (reminder)',
      subject: 'Email subject',
      body: 'Email body',
      encrypted: 'Encrypt this email',
    },
  },
};

export default i18n;
