const i18n = {
  messages: {
    fr: {
      'OpenEx - Crisis management exercises platform':
        'OpenEx - Plateforme d’exercices de crise',
      'Email address': 'Adresse email',
      Password: 'Mot de passe',
      'Sign in': "S'identifier",
      Dashboard: 'Tableau de bord',
      Exercises: 'Exercices',
      Players: 'Joueurs',
      Organizations: 'Organisations',
      Documents: 'Documents',
      Integrations: 'Intégrations',
      Settings: 'Configuration',
      Profile: 'Profil',
      Logout: 'Se déconnecter',
      Firstname: 'Prénom',
      Lastname: 'Nom de famille',
      Organization: 'Organisation',
      Language: 'Langue',
      Injects: 'Stimulis',
      Messages: 'Messages',
      'Recent exercises': 'Exercices récents',
      'No audiences in this exercise.': 'Aucune audience dans cet exercice.',
      'No exercises in this platform.': 'Aucun exercice dans cette plateforme.',
      'Injects distribution': 'Distribution des stimulis',
      'Next injects to send': 'Prochains stimlis à envoyer',
      'Organizations distribution across exercises':
        'Distribution des organisations dans les exercices',
      'Players distribution': 'Distribution des joueurs',
      Name: 'Nom',
      Subtitle: 'Sous-titre',
      'Start date': 'Date de début',
      'End date': 'Date de fin',
      Tags: 'Tags',
      'Create a new exercise': 'Créer un nouvel exercice',
      'Do you want to delete this player?':
        'Souhaitez-vous supprimer ce joueur ?',
      'Do you want to delete this inject?':
        'Souhaitez-vous supprimer ce stimuli ?',
      'Start date (optional)': 'Date de début (optionnel)',
      'Create a new player': 'Créer un nouveau joueur',
      'Update the player': 'Modifier le joueur',
      'one month': 'un mois',
      'Phone number (mobile)': 'Numéro de téléphone (mobile)',
      'Phone number (fix)': 'Numéro de téléphone (fixe)',
      'PGP public key': 'Clé publique PGP',
      'Create a new organization': 'Créer une nouvelle organisation',
      'Update the organization': "Modifier l'organisation",
      'Do you want to delete this organization?':
        'Souhaitez-vous supprimer cette organisation ?',
      Manual: 'Manuel',
      Parameters: 'Paramètres',
      'Default theme': 'Thème par défaut',
      'Default language': 'Langue par défaut',
      'Create a user': 'Créer un utilisateur',
      Administrator: 'Administrateur',
      Automatic: 'Automatique',
      'Passwords do no match': 'Les mots de passe ne correspondent pas',
      'Update the user password': "Modifier le mot de passe de l'utilisateur",
      'Update password': 'Modifier le mot de passe',
      Users: 'Utilisateurs',
      Groups: 'Groupes',
      'Create a new group': 'Créer un groupe',
      'Create a new tag': 'Créer un nouveau tag',
      'Do you want to delete this tag?': 'Souhaitez-vous supprimer ce tag ?',
      'Update the tag': 'Modifier le tag',
      'Manage grants': 'Gérer les permissions',
      'Manage users': 'Gérer les utilisateurs',
      'Do you want to delete this user?':
        'Souhaitez-vous supprimer cet utilisateur ?',
      'Do you want to delete this group?':
        'Souhaitez-vous supprimer ce groupe ?',
      'No tag': 'Aucun tag',
      'Update the user': "Modifier l'utilisateur",
      Exercise: 'Exercice',
      'Read/Write': 'Lecture/Ecriture',
      'Read Only': 'Lecture Seule',
      'Update the group': 'Modifier le groupe',
      Value: 'Valeur',
      Color: 'Couleur',
      Cancel: 'Annuler',
      Next: 'Suivant',
      Create: 'Créer',
      Launch: 'Lancer',
      Update: 'Modifier',
      Delete: 'Supprimer',
      Confirmation: 'Confirmation',
      Search: 'Rechercher',
      Required: 'Obligatoire',
      'Platform name': 'Nom de la plateforme',
      'Components version': 'Version des composants',
      Dark: 'Sombre',
      Light: 'Clair',
      'This field is required.': 'Ce champ est requis.',
      'The element has been updated': "L'élément a été modifié.",
      'The element already exists': "L'élément existe déjà.",
      'Manage the users of this group': 'Gérer les utilisateurs de ce groupe',
      'Create a new document': 'Créer un nouveau document',
      Close: 'Fermer',
      'Export to XLS': 'Exporter en XLS',
      Copy: 'Copier',
      Start: 'Démarrer',
      Status: 'Statut',
      Information: 'Information',
      Control: 'Contrôle',
      Scheduled: 'Planifié',
      Finished: 'Terminé',
      Execution: 'Exécution',
      Dryrun: 'Simulation',
      Comcheck: 'Vérification',
      Send: 'Envoyer',
      Remove: 'Retirer',
      Add: 'Ajouter',
      Scenario: 'Scénario',
      Title: 'Titre',
      Enabled: 'Activé',
      Disabled: 'Désactivé',
      Days: 'Jours',
      Hours: 'Heures',
      Minutes: 'Minutes',
      Seconds: 'Secondes',
      'Try the inject': 'Tester le stimuli',
      'Select a file': 'Sélectionner un fichier',
      'Do you want to delete this document?':
        'Souhaitez-vous supprimer ce document ?',
      'Add attachments': 'Ajouter des pièces jointes',
      'Add attachments in this inject':
        'Ajouter des pièces jointes dans ce stimuli',
      'Update the document': 'Modifier le document',
      'Inject data': 'Données du stimuli',
      'Add target audiences in this inject':
        'Ajouter des audiences cibles dans ce stimuli',
      'Targeted audiences': 'Audiences ciblées',
      'Test the inject': 'Tester le stimuli',
      'All audiences': 'Toutes les audiences',
      'Add target audiences': 'Ajouter des audiences cibles',
      'Trigger after': 'Se déclenche après',
      'Create a new inject': 'Créer un nouveau stimuli',
      'Remove from the audience': "Retirer de l'audience",
      'Update the audience': "Modifier l'audience",
      'Update the exercise': "Modifier l'exercice",
      'Update the inject': 'Modifier le stimuli',
      'Do you want to remove the player from the audience?':
        'Souhaitez-vous retirer le joueur de cette audience ?',
      'Add players in this audience': 'Ajouter des joueurs dans cette audience',
      'Create a new audience': 'Créer une nouvelle audience',
      'Remove from the inject': 'Retirer du stimuli',
      'Do you want to remove the audience from the inject?':
        "Souhaitez-vous retirer l'audience du stimuli ?",
      'Do you want to delete this exercise?':
        'Souhaitez-vous supprimer cet exercice ?',
      'Number of injects': 'Nombre de stimulis',
      'No organizations in this platform':
        'Aucune organisation dans cette plateforme.',
      'No injects to send in this platform.':
        'Aucun stimuli à envoyer dans cette plateforme.',
      'Before starting the exercise, you can launch a comcheck to validate player email addresses and a dryrun to send injects to the animation team.':
        "Avant de démarrer l'exercice, vous pouvez lancer une vérification pour valider les adresses emails et une simulation pour envoyer les stimulis à l'équipe d'animation.",
      'Auto assign': 'Auto assignation',
      'Auto observer': 'Auto observateur',
      'Auto planner': 'Auto planificateur',
      'The new users will automatically be assigned to this group.':
        'Les nouveaux utilisateurs seront automatiquement assignés à ce groupe.',
      'This group will have observer permission on new exercises.':
        "Ce groupe aura la permission d'observateur sur les nouveaux exercices.",
      'This group will have planner permission on new exercises.':
        'Ce groupe aura la permission de planificateur sur les nouveaux exercices.',
      'Processed injects': 'Stimulis traités',
      'Pending injects': 'Stimulis en attente',
      'No audience': 'Aucune audience',
      'No processed injects in this exercise.':
        'Aucun stimuli traité dans cet exercice.',
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_manual: 'Manuel (rappel)',
      subject: 'Sujet du mail',
      body: 'Corps du mail',
      encrypted: 'Chiffrer ce mail',
      content: 'Contenu et explications',
      'Executed in': 'Exécuté en',
      Success: 'Succès',
      m: 'm',
      h: 'h',
      d: 'j',
      'Do you want to change the status of this exercise?':
        'Souhaitez-vous changer le statut de cet exercice ?',
      Confirm: 'Confirmer',
      'Sender email address': "Adresse email de l'expéditeur",
      'Creation date': 'Date de création',
      'Next inject': 'Prochain stimuli',
      'Dangerous zone': 'Zone sensible',
      'Invalid user or password': "Nom d'utilisateur ou mot de passe incorrect",
      Default: 'Défaut',
      attachments: 'Pièces jointes',
      Mandatory: 'Requis',
      Optional: 'Optionnel',
      text: 'Champ texte',
      richtextarea: 'Zone de texte enrichie',
      textarea: 'Zone de texte',
      checkbox: 'Case à cocher',
      attachment: 'Fichier',
    },
    en: {
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_manual: 'Manual (reminder)',
      subject: 'Email subject',
      body: 'Email body',
      encrypted: 'Encrypt this email',
      content: 'Content and explanations',
      attachments: 'Attachments',
      text: 'Text field',
      richtextarea: 'Enriched text area',
      textarea: 'Text area',
      checkbox: 'Checkbox',
      attachment: 'File',
    },
  },
};

export default i18n;
