/* eslint-disable no-template-curly-in-string */
const i18n = {
  messages: {
    fr: {
      'OpenEx - Crisis management exercises platform':
        'OpenEx - Plateforme d’exercices de crise',
      'Email address': 'Adresse email',
      Password: 'Mot de passe',
      'Password validation': 'Validation du mot de passe',
      'Change your password': 'Changer votre mot de passe',
      'I forgot my password': "J'ai oublié mon mot de passe",
      'Send reset code': 'Envoyer le code',
      'Enter code': 'Entrer le code',
      'Back to login': "Retour à l'identification",
      'Sign in': "S'identifier",
      'Login with github': "S'identifier avec github",
      'You probably need a public email in your github account':
        "Vous avez probablement besoin d'une adresse e-mail publique dans votre compte github",
      'Should be a valid email address': 'Doit être une adresse e-mail valide',
      'Login with microsoft': "S'identifier avec microsoft",
      Continue: 'Continuer',
      Dashboard: 'Tableau de bord',
      Exercises: 'Exercices',
      Players: 'Joueurs',
      Organizations: 'Organisations',
      Documents: 'Documents',
      Integrations: 'Intégrations',
      Settings: 'Configuration',
      Profile: 'Profil',
      Logout: 'Se déconnecter',
      Firstname: 'Prénom',
      Lastname: 'Nom de famille',
      Organization: 'Organisation',
      Language: 'Langue',
      Injects: 'Stimulis',
      Messages: 'Messages',
      Mails: 'Mails',
      Timeline: 'Chronologie',
      Definition: 'Définition',
      Results: 'Résultats',
      Medias: 'Médias',
      Submit: 'Soumettre',
      Country: 'Pays',
      Flag: 'Flag',
      Flags: 'Flags',
      'Flag type': 'Type de flag',
      'Flag is correct! It has been successfully submitted.':
        'Le flag est correct! Il a été soumis avec succès.',
      'Flag is not correct! Try again...':
        'Le flag est incorrect! Merci de rééssayer...',
      'Preview challenges page': 'Aperçu des challenges',
      'Switch to preview mode': 'Basculer en mode aperçu',
      'Switch to player mode': 'Basculer en mode joueur',
      'Create a new media': 'Créer un nouveau média',
      'Update the media': 'Modifier le média',
      'Recent exercises': 'Exercices récents',
      'No audiences in this exercise.': 'Aucune audience dans cet exercice.',
      'No exercises in this platform.': 'Aucun exercice dans cette plateforme.',
      'Injects distribution': 'Distribution des stimulis',
      'Next injects to send': 'Prochains stimlis à envoyer',
      'Organizations distribution across exercises':
        'Distribution des organisations dans les exercices',
      'Players distribution': 'Distribution des joueurs',
      'Inject context': 'Contexte du stimuli',
      'added an entry on': 'a ajouté une entrée le',
      'This file type is not accepted here.':
        "Ce type de fichier n'est pas accepté ici",
      'Distribution of score by audience (in % of expectations)':
        'Distribution du score par audience (en % des attendus)',
      'Select all': 'Sélectionner tout',
      'Do you want to anonymize lessons learned questionnaire?':
        "Souhaitez-vous anonymiser le questionnaire de retour d'expérience ?",
      'You will not be able to change this setting later.':
        'Vous ne serez plus en mesure de modifier ce paramètre après.',
      Stop: 'Arrêter',
      Name: 'Nom',
      Subtitle: 'Sous-titre',
      'Start date': 'Date de début',
      'End date': 'Date de fin',
      To: 'A',
      From: 'De',
      Tags: 'Tags',
      Reply: 'Répondre',
      newspaper: 'Journal',
      tv: 'Chaîne de télévision',
      Anonymize: 'Anonymiser',
      microblogging: 'Microblogging',
      'Targeted players': 'Joueurs ciblés',
      'Inject details': 'Détails du stimuli',
      'Export this list': 'Exporter cette liste',
      'Create a new exercise': 'Créer un nouvel exercice',
      'Do you want to delete this audience?':
        'Souhaitez-vous supprimer cette audience ?',
      'Do you want to delete this comcheck?':
        'Souhaitez-vous supprimer cette vérification ?',
      'Do you want to delete this player?':
        'Souhaitez-vous supprimer ce joueur ?',
      'Do you want to delete this inject?':
        'Souhaitez-vous supprimer ce stimuli ?',
      'Do you want to delete this media?':
        'Souhaitez-vous supprimer ce média ?',
      'Start date (optional)': 'Date de début (optionnel)',
      'Create a new player': 'Créer un nouveau joueur',
      'Update the player': 'Modifier le joueur',
      'one month': 'un mois',
      'Phone number (mobile)': 'Numéro de téléphone (mobile)',
      'Phone number (fix)': 'Numéro de téléphone (fixe)',
      'PGP public key': 'Clé publique PGP',
      'Create a new organization': 'Créer une nouvelle organisation',
      'Update the organization': "Modifier l'organisation",
      'Do you want to delete this organization?':
        'Souhaitez-vous supprimer cette organisation ?',
      'Mail sent to': 'Mail envoyé à',
      'Audiences scores over time (in % of expectations)':
        'Score des audience dans le temps (en % des attendus)',
      'Distribution of total score by inject type':
        'Distribution du score total par type de stimuli',
      on: 'le',
      Manual: 'Manuel',
      'Total score': 'Score total',
      'Media entries': 'Entrées de média',
      Parameters: 'Paramètres',
      'Default theme': 'Thème par défaut',
      'Default language': 'Langue par défaut',
      'Do you want to trigger this inject now?':
        'Souhaitez-vous déclencher ce stimuli maintenant ?',
      Administrator: 'Administrateur',
      'Trigger now': 'Déclencher maintenant',
      Automatic: 'Automatique',
      'Passwords do no match': 'Les mots de passe ne correspondent pas',
      'Update the user password': "Modifier le mot de passe de l'utilisateur",
      'Update password': 'Modifier le mot de passe',
      'Current password': 'Mot de passe actuel',
      'New password': 'Nouveau mot de passe',
      Users: 'Utilisateurs',
      Groups: 'Groupes',
      'Create a new group': 'Créer un groupe',
      'Create a new tag': 'Créer un nouveau tag',
      'Do you want to delete this tag?': 'Souhaitez-vous supprimer ce tag ?',
      'Update the tag': 'Modifier le tag',
      'Manage grants': 'Gérer les permissions',
      'Manage users': 'Gérer les utilisateurs',
      'Manage players': 'Gérer les joueurs',
      'Do you want to delete this user?':
        'Souhaitez-vous supprimer cet utilisateur ?',
      'Do you want to delete this group?':
        'Souhaitez-vous supprimer ce groupe ?',
      'No tag': 'Aucun tag',
      'Update the user': "Modifier l'utilisateur",
      Exercise: 'Exercice',
      'Read/Write': 'Lecture/Ecriture',
      'Read Only': 'Lecture Seule',
      'Update the group': 'Modifier le groupe',
      Value: 'Valeur',
      Color: 'Couleur',
      Cancel: 'Annuler',
      Next: 'Suivant',
      Create: 'Créer',
      Launch: 'Lancer',
      Update: 'Modifier',
      Delete: 'Supprimer',
      Confirmation: 'Confirmation',
      Search: 'Rechercher',
      Required: 'Obligatoire',
      'Technical targets': 'Cibles techniques',
      'Platform name': 'Nom de la plateforme',
      'Components version': 'Version des composants',
      'Sent at': 'Envoyé le',
      'Mails not read': 'Mails non lus',
      'Total mails': 'Mails totaux',
      Dark: 'Sombre',
      Light: 'Clair',
      'This field is required.': 'Ce champ est requis.',
      'The element has been updated': "L'élément a été modifié.",
      'The element already exists': "L'élément existe déjà.",
      'Manage the users of this group': 'Gérer les utilisateurs de ce groupe',
      'Create a new document': 'Créer un nouveau document',
      Close: 'Fermer',
      'Export to XLS': 'Exporter en XLS',
      'Export to image': 'Exporter en image',
      'Export to PDF': 'Exporter en PDF',
      'Export to CSV': 'Exporter en CSV',
      Copy: 'Copier',
      Start: 'Démarrer',
      Status: 'Statut',
      Information: 'Information',
      Control: 'Contrôle',
      Scheduled: 'Planifié',
      Finished: 'Terminé',
      Execution: 'Exécution',
      Dryrun: 'Simulation',
      Comcheck: 'Vérification',
      Send: 'Envoyer',
      Remove: 'Retirer',
      Add: 'Ajouter',
      Scenario: 'Scénario',
      Title: 'Titre',
      Enabled: 'Activé',
      Disabled: 'Désactivé',
      Days: 'Jours',
      Hours: 'Heures',
      Minutes: 'Minutes',
      Seconds: 'Secondes',
      'Try the inject': 'Tester le stimuli',
      File: 'Fichier',
      'Select a file': 'Sélectionner un fichier',
      'Do you want to delete this document?':
        'Souhaitez-vous supprimer ce document ?',
      'Update the document': 'Modifier le document',
      'Inject data': 'Données du stimuli',
      'Add target audiences in this inject':
        'Ajouter des audiences cibles dans ce stimuli',
      'Targeted audiences': 'Audiences ciblées',
      'Test the inject': 'Tester le stimuli',
      'All audiences': 'Toutes les audiences',
      'Add target audiences': 'Ajouter des audiences cibles',
      'Trigger after': 'Se déclenche après',
      'Create a new inject': 'Créer un nouveau stimuli',
      'Remove from the audience': "Retirer de l'audience",
      'Update the audience': "Modifier l'audience",
      'Update the exercise': "Modifier l'exercice",
      'Update the inject': 'Modifier le stimuli',
      'Do you want to remove the player from the audience?':
        'Souhaitez-vous retirer le joueur de cette audience ?',
      'Add players in this audience': 'Ajouter des joueurs dans cette audience',
      'Create a new audience': 'Créer une nouvelle audience',
      'Remove from the inject': 'Retirer du stimuli',
      'Remove from the element': "Retirer de l'élément",
      'Do you want to remove the audience from the inject?':
        "Souhaitez-vous retirer l'audience du stimuli ?",
      'Do you want to delete this exercise?':
        'Souhaitez-vous supprimer cet exercice ?',
      'Number of injects': 'Nombre de stimulis',
      'No organizations in this platform':
        'Aucune organisation dans cette plateforme.',
      'No injects to send in this platform.':
        'Aucun stimuli à envoyer dans cette plateforme.',
      'Before starting the exercise, you can launch a comcheck to validate player email addresses and a dryrun to send injects to the animation team.':
        "Avant de démarrer l'exercice, vous pouvez lancer une vérification pour valider les adresses emails et une simulation pour envoyer les stimulis à l'équipe d'animation.",
      'Applying a template will add all categories and questions of the selected template to this exercise.':
        'Appliquer un template va ajouter toutes les catégories et questions du template sélectionné à cet exercice.',
      'Apply a template': 'Appliquer un template',
      'Auto assign': 'Auto assignation',
      'Auto observer': 'Auto observateur',
      'Auto planner': 'Auto planificateur',
      'The new users will automatically be assigned to this group.':
        'Les nouveaux utilisateurs seront automatiquement assignés à ce groupe.',
      'This group will have observer permission on new exercises.':
        "Ce groupe aura la permission d'observateur sur les nouveaux exercices.",
      'This group will have planner permission on new exercises.':
        'Ce groupe aura la permission de planificateur sur les nouveaux exercices.',
      'Processed injects': 'Stimulis traités',
      'Pending injects': 'Stimulis en attente',
      'No audience': 'Aucune audience',
      'No processed injects in this exercise.':
        'Aucun stimuli traité dans cet exercice.',
      'No pending injects in this exercise.':
        'Aucun stimuli en attente dans cet exercice.',
      'Add media pressure in this inject':
        'Ajouter de la pression médiatique dans ce stimuli',
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_mastodon: 'Mastodon',
      openex_lade: 'Airbus LADE',
      openex_gnu_social: 'GNU Social',
      openex_twitter: 'Twitter',
      openex_http: 'Requête HTTP',
      openex_manual: 'Manuel (rappel)',
      Subject: 'Sujet du mail',
      Body: 'Corps du mail',
      Encrypted: 'Chiffrer ce mail',
      Attachments: 'Pièces jointes',
      Attachment: 'Pièce jointe',
      Content: 'Contenu',
      Audiences: 'Audiences',
      'Send email': 'Envoyer le mail',
      'Inject expectations': 'Attendus du stimuli',
      'Add documents in this media pressure':
        'Ajouter des documents à cette pression médiatique',
      'Expect audiences to read the article(s)':
        'Les audiences doivent lire le(s) article(s)',
      'Add media pressure': 'Ajouter de la pression médiatique',
      'Remove from the medias pressure': 'Supprimer de la pression médiatique',
      'Raw request data': 'Données brutes de la requête',
      'Media pressure to publish': 'Pression médiatique à publier',
      'Form request data': 'Données de formulaire de la requête',
      Key: 'Clé',
      Headers: 'En-têtes',
      audience: 'Audience',
      attachment: 'Document',
      'Executed in': 'Exécuté en',
      'Use basic authentication': 'Utiliser une authentification basique',
      Success: 'Succès',
      m: 'm',
      h: 'h',
      d: 'j',
      'Do you want to change the status of this exercise?':
        'Souhaitez-vous changer le statut de cet exercice ?',
      Confirm: 'Confirmer',
      Text: 'Texte',
      'Sender email address': "Adresse email de l'expéditeur",
      'Creation date': 'Date de création',
      'Next inject': 'Prochain stimuli',
      'Dangerous zone': 'Zone sensible',
      'Invalid user or password': "Nom d'utilisateur ou mot de passe incorrect",
      Default: 'Défaut',
      Mandatory: 'Requis',
      Optional: 'Optionnel',
      text: 'Champ texte',
      textarea: 'Zone de texte',
      tuple: 'Duo clef valeur',
      checkbox: 'Case à cocher',
      'Do you want to try this inject?': 'Souhaitez-vous tester ce stimuli ?',
      'The inject will only be sent to you.':
        'Le stimuli sera uniquement envoyé à vous même.',
      Try: 'Tester',
      Disable: 'Désactiver',
      Enable: 'Activer',
      'Mark as done': 'Marquer comme fait',
      'Do you want to mark this inject as done?':
        'Souhaitez-vous marquer ce stimuli comme fait ?',
      Mark: 'Marquer',
      'Do you want to disable this inject?':
        'Souhaitez-vous désactiver ce stimuli ?',
      'Do you want to enable this inject?':
        'Souhaitez-vous activer ce stimuli ?',
      'Do you want to disable this audience?':
        'Souhaitez-vous désactiver cette audience ?',
      'Do you want to enable this audience?':
        'Souhaitez-vous activer cette audience ?',
      Trigger: 'Déclencheur',
      'Manage content': 'Gérer le contenu',
      Controls: 'Contrôles',
      'Lessons learned': 'Expérience',
      Planning: 'Planification',
      'Media pressure': 'Pression médiatique',
      Comchecks: 'Vérifications',
      Dryruns: 'Simulations',
      'Messages header': 'En-tête des messages',
      'Messages footer': 'Pied des messages',
      'Send a new comcheck': 'Envoyer une nouvelle vérification',
      'Launch a new dryrun': 'Démarrer une nouvelle simulation',
      Hello: 'Bonjour',
      Statistics: 'Statistiques',
      Reports: 'Rapports',
      '[${exercise.name}] Communication check':
        '[${exercise.name}] Vérification des moyens de communication',
      'This is a communication check before the beginning of the exercise. Please click on the following link in order to confirm you successfully received this message: <a href="${comcheck.url}">${comcheck.url}</a>.':
        'Ceci est une vérification des moyens de communication avant le début de l\'exercice. Merci de bien vouloir cliquer sur le lien ci-dessous afin de confirmer que vous avez reçu ce message avec succès : <a href="${comcheck.url}">${comcheck.url}</a>.',
      'We would like thank your for your participation in this exercise. You are kindly requested to fill this lessons learned questionnaire: <a href="${lessons_uri}">${lessons_uri}</a>.':
        "Nous souhaitons vous remercier pour votre participation à l'exercice. Vous êtes cordialement invités à remplir le formulaire de retour d'expérience : <a href=\"${lessons_uri}\">${lessons_uri}</a>.",
      '[${exercise.name}] Lessons learned questionnaire':
        "[${exercise.name}] Questionnaire de retour d'expérience",
      'Best regards': 'Bien cordialement',
      'The exercise control team': "L'équipe d'animation de l'exercice",
      'Do you want to launch a new dryrun?':
        'Souhaitez-vous lancer une nouvelle simulation ?',
      'Add tags to this exercise': 'Ajouter des tags à cet exercice',
      'No comcheck in this exercise.': 'Aucune vérification dans cet exercice',
      'There is nothing to see here...': "Il n'y a rien à voir ici...",
      'Send the lessons learned questionnaire':
        "Envoyer le questionnaire de retour d'expérience",
      Comments: 'Commentaires',
      'Comment (optional)': 'Commentaire (optionnel)',
      "What didn't work well": "Ce qui n'a pas bien fonctionné",
      'What worked well': 'Ce qui a bien fonctionné',
      'Global evaluation': 'Evaluation globale',
      'Your overall evaluation about this question.':
        'Votre évaluation générale à propos de cette question.',
      'Do you want to submit your answers? You will not be able to change them later.':
        'Souhaitez-vous soumettre vos réponses ? Vous ne pourrez pas les changer plus tard.',
      Check: 'Vérification',
      Preview: 'Aperçu',
      None: 'Aucune',
      message: 'Message',
      Pending: 'En attente',
      State: 'Etat',
      'Sent date': "Date d'envoi",
      'Received date': 'Date de réception',
      'Communication check': 'Vérification des moyens de communication',
      Running: 'En cours',
      Failure: 'Echec',
      Expired: 'Expiré',
      Anonymized: 'Anonymisé',
      'No media pressure entry in this media yet.':
        'Encore aucune entrée de pression médiatique dans ce média.',
      'Your communication check is': 'Votre test de communication est',
      successful: 'un succès',
      answers: 'réponses',
      'of which': 'dont',
      'contain comments': 'contiennent des commentaires',
      'Verification done at': 'Vérification faite le',
      'No dryrun in this exercise.': 'Aucune simulation dans cet exercice.',
      'No objectives in this exercise.': 'Aucun objectif dans cet exercice.',
      'There is no evaluation for this objective yet': 'Il n’y a pas encore d’évaluation pour cet objectif',
      'No polls in this exercise.': 'Aucun sondage dans cet exercice',
      'Do you want to delete this dryrun?':
        'Souhaitez-vous supprimer cette simulation ?',
      'Overall objectives score': 'Score global des objectifs',
      'Do you want to delete this poll?':
        'Souhaitez-vous supprimer ce sondage ?',
      'Update the poll': 'Modifier le sondage',
      'Exercise logs': "Journal d'exercice",
      'Poll replies': 'Réponses au sondage',
      Overview: 'Aperçu',
      Objectives: 'Objectifs',
      'Create a new objective': 'Créer un nouvel objectif',
      'Update the objective': "Modifier l'objectif",
      'Do you want to delete this objective?':
        'Souhaitez-vous supprimer cet objectif ?',
      'Write an entry': 'Ecrire une entrée',
      'Do you want to delete this log?':
        'Souhaitez-vous supprimer cette entrée ?',
      'Objective achievement evalution':
        "Evaluation de l'atteinte de l'objectif",
      Evaluate: 'Evaluer',
      'My evaluation': 'Mon évaluation',
      Priority: 'Priorité',
      Polls: 'Sondages',
      'Create a new poll': 'Créer un nouveau sondage',
      'Update the log': "Modifier l'entrée",
      'Create a new user': 'Créer un nouvel utilisateur',
      'Dryrun recipients': 'Destinataires de la simulation',
      'Create a new report': 'Créer un nouveau rapport',
      'Do you want to delete this report?':
        'Souhaitez-vous supprimer ce rapport ?',
      'Update the report': 'Modifier le rapport',
      token: 'Token du compte',
      status: 'Statut',
      'Inject documents': 'Documents du stimuli',
      'Add documents': 'Ajouter des documents',
      'Add documents in this inject': 'Ajouter des documents dans ce stimuli',
      Yes: 'Oui',
      No: 'Non',
      'Not applicable': 'Non applicable',
      'Enable attachment': 'Activer la pièce jointe',
      'Disable attachment': 'Désativer la pièce jointe',
      'Do you want to remove the document from the element?':
        'Souhaitez-vous retirer ce document de cet élément ?',
      'Import an exercise': 'Importer un exercice',
      Export: 'Exporter',
      'Export the exercise': 'Exporter cet exercice',
      'Reset to default values': 'Réinitialiser les valeurs par défaut',
      Elements: 'Eléments',
      'Scenario (including attached files)':
        'Scénario (fichiers joints inclus)',
      'Send an email': 'Envoyer un email',
      'Send a SMS': 'Envoyer un SMS',
      'To fill': 'A remplir',
      Username: "Nom d'utilisateur",
      Unknown: 'Inconnu',
      'Primary color (dark)': 'Couleur primaire (sombre)',
      'Secondary color (dark)': 'Couleur secondaire (sombre)',
      'Primary color (light)': 'Couleur primaire (clair)',
      'Secondary color (light)': 'Couleur secondaire (clair)',
      logo: 'Logo seulement',
      title: 'Titre seulement',
      'logo-title': 'Logo et titre',
      'Dark theme': 'Thème sombre',
      'Light theme': 'Thème clair',
      'Header mode': 'Mode du bandeau supérieur',
      'Select an image': 'Sélectionner une image',
      'Create an image': 'Créer une image',
      'Change logo': 'Changer le logo',
      'Scheduled / in use': 'Planifié / utilisé',
      'Not used in the exercise': "Pas utilisé dans l'exercice",
      'Update the media pressure': 'Modifier la pression médiatique',
      'Do you want to delete this media pressure?':
        'Souhaitez-vous supprimer cette pression médiatique ?',
      'Do you want to delete this challenge?':
        'Souhaitez-vous supprimer ce challenge ?',
      'Do you want to delete this lessons learned category?':
        "Souhaitez-vous supprimer cette catégorie de retour d'expérience ?",
      'Update the lessons learned category':
        "Modifier une catégorie de retour d'expérience",
      'Create a new media pressure': 'Créer une nouvelle pression médiatique',
      'Create a new lessons learned question':
        "Créer une nouvelle question de retour d'expérience",
      'Collaborative lessons learned': "Retour d'expérience collaboratif",
      'Create a new lessons learned category':
        "Créer une catégorie de retour d'expérience",
      'Do you want to delete this lessons learned question?':
        "Souhaitez-vous supprimer cette question de retour d'expérience ?",
      'Update the lessons learned question':
        "Modifier la question de retour d'expérience",
      Answers: 'Réponses',
      'Categories and questions': 'Catégories et questions',
      Questions: 'Questions',
      Empty: 'Vider',
      'Objective achievement evaluation':
        "Evaluation de l'atteinte de l'objectif",
      'Crisis intensity (injects by hour)':
        'Intensité de la crise (stimulis par heure)',
      'Apply a lessons learned template':
        "Appliquer un template de retour d'expérience",
      'Questionnaire mode': 'Mode du questionnaire',
      'Anonymize answers': 'Anonymiser les réponses',
      'No explanation': 'Aucune explication',
      'Add target audiences in this lessons learned category':
        "Ajouter des audiences cibles à cette catégorie de retour d'expérience",
      'Sending the questionnaire will emit an email to each player with a unique link to access and fill it.':
        'Envoyer le questionnaire va émettre un email à chaque joueur avec un lien unique pour y accéder et le remplir.',
      'Do you want to empty lessons learned categories and questions?':
        "Souhaitez-vous vider les catégories et les questions de retour d'expérience ?",
      'Do you want to reset lessons learned answers?':
        "Souhaitez-vous réinitialiser les réponses du retour d'expérience ?",
      Reset: 'Réinitialiser',
      Campaign: 'Campagne',
      Duration: 'Durée',
      'Send the questionnaire': 'Envoyer le questionnaire',
      'Reset answers': 'Réinitialiser les réponses',
      hours: 'heures',
      Apply: 'Appliquer',
      players: 'joueurs',
      Explanation: 'Explication',
      Category: 'Catégorie',
      'Create a new challenge': 'Créer un nouveau challenge',
      'Create a new lessons learned template':
        "Créer un nouveau template de retour d'expérience",
      'Update the lessons learned template':
        "Modifier le template de retour d'expérience",
      'Do you want to delete this lessons learned template?':
        "Souhaitez-vous supprimer ce template de retour d'expérience ?",
      Media: 'Média',
      Author: 'Auteur',
      'Max number of attempts': "Nombre maximum d'essais",
      'Add documents in this challenge': 'Ajouter un document à ce challenge',
      'At least one flag is required for a challenge.':
        'Au moins un flag est requis pour un challenge.',
      'Text (case-sensitive)': 'Texte (sensible à la casse)',
      'Regular expression': 'Expression régulière',
      'Update the challenge': 'Modifier le challenge',
      'Challenges to publish': 'Challenges à publier',
      'Add challenge in this inject': 'Ajouter des challenges à ce stimuli',
      'Add challenges': 'Ajouter des challenges',
      'Do you want to remove this media pressure from the inject?':
        'Souhaitez-vous retirer cette pression médiatique de ce stimuli ?',
      'Do you want to remove this challenge from the inject?':
        'Souhaitez-vous retirer ce challenge de ce stimuli ?',
      VALUE: 'Texte',
      VALUE_CASE: 'Texte (sensible à la casse)',
      REGEXP: 'Expression régulière',
      'No category': 'Aucune catégorie',
      'No challenge in this exercise yet.':
        'Encore aucun challenge dans cet exercice.',
      'Distribution of expectations by audience':
        'Distribution des attendus par audience',
      'Distribution of expectations by inject type':
        'Distribution des attendus par type de stimuli',
      'Distribution of expected total score by inject type':
        'Distribution du score total attendu par type de stimuli',
      '-': 'Aucun',
      'Each audience should upload a document':
        'Chaque audience doit uploader un document',
      'Each audience should submit a text response':
        'Chaque audience doit soumettre une réponse texte',
      Expectation: 'Attendu',
      'Expectation score': "Score de l'attendu",
      'Distribution of expected total score by audience':
        'Distribution du score total attendu par audience',
      'Exercise definition and scenario':
        "Définition de l'exercice et scénario",
      'Exercise results': "Résultats de l'exercice",
      'Exercise data': "Données de l'exercice",
      'Distribution of total score by audience':
        'Distribution du score total par audience',
      'Distribution of total score by organization':
        'Distribution du score total par organisation',
      'Number of expectations': "Nombre d'attendus",
      'Total expected score': 'Score total attendu',
      'Distribution of total score by player':
        'Distribution du score total par joueur',
      'Distribution of total score by inject':
        'Distribution du score total par stimuli',
      'Distribution of injects by type': 'Distribution des stimulis par type',
      'Distribution of injects by audience':
        'Distribution des stimulis par audience',
      'Distribution of mails by audience':
        'Distribution des mails par audience',
      'Distribution of mails by player': 'Distribution des mails par joueur',
      'Distribution of mails by inject': 'Distribution des mails par stimuli',
      'Sent injects over time': 'Stimulis envoyés dans le temps',
      'Sent mails over time': 'Emails envoyés dans le temps',
      'No data to display or the exercise has not started yet':
        "Aucune donnée disponible ou l'exercice n'a pas encore commencé",
      'Back to administration': "Retour à l'administration",
      'Audiences scores over time': 'Score des audiences dans le temps',
      'Inject types scores over time':
        'Score des types de stimuli dans le temps',
      'The animation team can validate the audience reaction':
        "L'équipe d'animation peut valider la réaction de l'audience",
      Description: 'Description',
      'No description': 'Aucune description',
      'Only injects with manual validation':
        'Seulement les stimulis avec validation manuelle',
      'Pending reading': 'Lecture en attente',
      'Pending submission': 'Soumission en attente',
      'Pending validation': 'Validation en attente',
      Validations: 'Validations',
      Type: 'Type',
      Validate: 'Valider',
      Validated: 'Validé',
      Error: 'Erreur',
      // Challenges
      Challenges: 'Challenges',
      // Variables
      'Available variables': 'Variables disponibles',
      Variables: 'Variables',
      'Create a new variable': 'Créer une nouvelle variable',
      'Do you want to delete the variable ?': 'Voulez vous supprimer cette variable ?',
      'Update the variable': 'Mettre à jour la variable',
      'Invalid input. Please use only letters or underscores, and ensure the field is not empty.':
        "Saisie invalide. Merci d'utiliser uniquement des lettres ou des tirets bas, et de vous assurer que le champ n'est pas vide.",
      'Builtin variables': 'Variables intégrées',
      'Custom variables': 'Variables personnalisées',
      'Please follow this link to': 'Merci de suivre ce lien pour',
      'manage custom variables': 'gérer les variables personnalisées',
      'view custom variables': 'afficher les variables personnalisées',
      'Variables with values': 'Variables avec valeurs',
      // MDEditor
      'Edit code': 'Edition',
      'Live code': 'Code en temps réel',
      'Preview code': 'Prévisualisation',
      Shares: 'Nombre de partages',
      Likes: 'Nombre de likes',
      'Read more': 'Lire plus',
      'JAVA Virtual Machine': 'Machine virtuelle JAVA',
      'Latest stable build': 'Dernière version stable',
      'API specifications': 'Spécifications de l\'API',
      Theme: 'Thème',
      'OpenEx platform': 'Plateforme OpenEx',
      PostgreSQL: 'PostgreSQL',
      'Token key': 'Token',
      Example: 'Exemple',
      Score: 'Score',
      Message: 'Message',
      'New control': 'Nouveau contrôle',
      'Percent of reached score': 'Pourcentage du score atteint',
      Pause: 'Pause',
      Resume: 'Reprendre',
      injects: 'Injecter',
      Paused: 'En pause',
      Canceled: 'Annulé',
      Partial: 'Partiel',
      'Quick inject definition': 'Définition rapide de l’injection',
      Order: 'Ordre',
      Details: 'Détails',
      Audience: 'Public',
      Template: 'Modèle',
      Questionnaire: 'Questionnaire',
      User: 'Utilisateur',
      'General information': 'Informations générales',
      'Exercise definition statistics': 'Statistiques de la définition de l’exercice',
      'Exercise definition scores': 'Scores de la définition de l’exercice',
      'Exercise data statistics': 'Statistiques des données de l’exercice',
      'Exercise results statistics': 'Statistiques des résultats de l’exercice',
      'Lessons learned objectives': 'Objectifs des leçons apprises',
      'Lessons learned statistics': 'Statistiques des leçons apprises',
      'Lessons learned details': 'Détails des leçons apprises',
      Logos: 'Logos',
      toggle: 'Basculer',
      Collapse: 'Réduire',
      Animation: 'Animation',
      'API access': 'Accès à l’API',
      RENEW: 'RENOUVELER',
      Granted: 'Accordé',
      submitted: 'Soumis',
      failed: 'Échoué',
      Question: 'Question',
      By: 'Par',
    },
    en: {
      openex_email: 'Email',
      openex_ovh_sms: 'SMS (OVH)',
      openex_mastodon: 'Mastodon',
      openex_manual: 'Manual (reminder)',
      openex_lade: 'Airbus LADE',
      openex_gnu_social: 'GNU Social',
      openex_twitter: 'Twitter',
      openex_http: 'HTTP Request',
      Subject: 'Email subject',
      Body: 'Email body',
      Encrypted: 'Encrypt this email',
      Attachments: 'Attachments',
      Audiences: 'Audiences',
      audience: 'Audience',
      text: 'Text field',
      textarea: 'Text area',
      tuple: 'Key value pair',
      checkbox: 'Checkbox',
      attachment: 'Document',
      message: 'Message',
      token: 'Account token',
      status: 'Status',
      Running: 'On-going',
      newspaper: 'Newspaper',
      tv: 'TV channel',
      microblogging: 'Microblogging',
      logo: 'Logo only',
      title: 'Title only',
      'logo-title': 'Logo and title',
      VALUE: 'Text',
      VALUE_CASE: 'Text (case-sensitive)',
      REGEXP: 'Regular expression',
      '-': 'None',
    },
  },
};

export default i18n;
