//region AVATAR
export const AVATAR_TYPE_TOPBAR = 'AVATAR_TYPE_TOPBAR';
export const AVATAR_TYPE_LIST = 'AVATAR_TYPE_LIST';
//endregion

//region ICON
export const ICON_TYPE_NAVBAR = 'ICON_TYPE_NAVBAR';
export const ICON_TYPE_LIST = 'ICON_TYPE_LIST';

export const ICON_NAME_LOCAL_MOVIES = 'ICON_NAME_LOCAL_MOVIES';
export const ICON_NAME_HARDWARE_COMPUTER = 'ICON_NAME_HARDWARE_COMPUTER';
export const ICON_NAME_SOCIAL_PERSON = 'ICON_NAME_SOCIAL_PERSON';
export const ICON_NAME_SOCIAL_GROUP = 'ICON_NAME_SOCIAL_GROUP';
export const ICON_NAME_CONTENT_ADD = 'ICON_NAME_CONTENT_ADD';
export const ICON_NAME_CONTENT_MAIL = 'ICON_NAME_CONTENT_MAIL';
export const ICON_NAME_ACTION_DELETE = 'ICON_NAME_ACTION_DELETE';
export const ICON_NAME_ACTION_SETTINGS = 'ICON_NAME_ACTION_SETTINGS';
export const ICON_NAME_ACTION_SCHEDULE = 'ICON_NAME_ACTION_SCHEDULE';
//endregion

//region APPBAR
export const APPBAR_TYPE_TOPBAR = 'APPBAR_TYPE_TOPBAR';
export const APPBAR_TYPE_LEFTBAR = 'APPBAR_TYPE_LEFTBAR';
//endregion

//region APPBAR
export const TOOLBAR_TYPE_LOGIN = 'TOOLBAR_TYPE_LOGIN';
//endregion