---
kind: pipeline
name: openbas-tests

steps:
  - name: api-tests
    image: maven:3.9.8-eclipse-temurin-22
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/openbas
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
    commands:
      - mvn clean install -q -DskipTests
      - cd openbas-api
      - mvn test -q
      - cd ../openbas-framework
      - mvn test -q

  - name: frontend-tests
    image: node:20-alpine
    volumes:
      - name: cache-node-frontend
        path: /drone/src/openbas-front/node_modules
    commands:
      - cd openbas-front
      - yarn install
      - yarn build
      - yarn check-ts
      - yarn lint
      - yarn i18n-checker
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

  - name: app-e2e
    image: maven:3.9.8-eclipse-temurin-22
    detach: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql-e2e:5432/openbas
      SPRING_DATASOURCE_USERNAME: openbas
      SPRING_DATASOURCE_PASSWORD: openbas
      MINIO_ENDPOINT: minio-e2e
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_ACCESS_SECRET: minioadmin
      OPENBAS_ADMIN_EMAIL: admin@openbas.io
      OPENBAS_ADMIN_PASSWORD: admin
      OPENBAS_ADMIN_TOKEN: 0d17ce9a-f3a8-4c6d-9721-c98dc3dc023f
    commands:
      - apt update && apt install -y gnupg
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      - apt update
      - apt install -y yarn
      - apt install -y nodejs
      - apt install -y git
      - cd openbas-front
      - yarn install
      - yarn build
      - cd ..
      - mvn install -DskipTests=true
      - java -jar openbas-api/target/openbas-api.jar
    depends_on:
      - api-tests
      - frontend-tests

  - name: frontend-e2e-tests
    image: node:20.17.0
    volumes:
      - name: cache-node-frontend-e2e
        path: /drone/src/openbas-front/node_modules
    commands:
      - apt update
      - apt -y install netcat-traditional
      - while ! nc -z app-e2e 8080 ; do sleep 1 ; done
      - cd openbas-front
      - yarn install
      - yarn playwright install --with-deps chromium
      - APP_URL=http://app-e2e:8080 yarn test:e2e
    depends_on:
      - app-e2e

  - name: codecov
    image: robertstettner/drone-codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - openbas-api/target/site/jacoco/jacoco.xml
        - openbas-framework/target/site/jacoco/jacoco.xml
    depends_on:
      - api-tests

  - name: build-circleci
    image: curlimages/curl
    commands:
      - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenBAS-Platform/openbas/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

  - name: build-circleci-release
    image: curlimages/curl
    commands:
      - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenBAS-Platform/openbas/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        - tag
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: drone
      channel: notifications
    when:
      status: [ success, failure ]
    depends_on:
      - api-tests
      - frontend-tests
      - frontend-e2e-tests

services:
  - name: minio
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]
  - name: pgsql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: openbas
      POSTGRES_PASSWORD: openbas
      POSTGRES_DB: openbas
  - name: minio-e2e
    image: minio/minio:RELEASE.2023-12-02T10-51-33Z-cpuv1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: [ server, /data ]
  - name: pgsql-e2e
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: openbas
      POSTGRES_PASSWORD: openbas
      POSTGRES_DB: openbas

volumes:
  - name: cache-node-frontend
    host:
      path: /tmp/cache-node-frontend
  - name: cache-node-frontend-e2e
    host:
      path: /tmp/cache-node-frontend-e2e
  - name: cache-python
    host:
      path: /tmp/cache-python
