FROM openjdk:21-jdk-slim AS app

WORKDIR /opt
RUN apt update && apt install -y tini git --no-install-recommends && rm -rf /var/lib/apt/lists/*
COPY openbas-build ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openbas-api.jar"]
