FROM maven:3.9.9-eclipse-temurin-21 AS api-builder

WORKDIR /opt/openbas-build/openbas
COPY openbas-model ./openbas-model
COPY openbas-framework ./openbas-framework
COPY openbas-api ./openbas-api
COPY openbas-front/builder/prod/build ./openbas-front/builder/prod/build
COPY pom.xml ./pom.xml
RUN mvn install -DskipTests -Pdev

FROM eclipse-temurin:21.0.3_9-jre AS app

RUN ln -s /usr/bin/dpkg-split /usr/sbin/dpkg-split
RUN ln -s /usr/bin/dpkg-deb /usr/sbin/dpkg-deb
RUN ln -s /bin/rm /usr/sbin/rm
RUN ln -s /bin/tar /usr/sbin/tar
RUN DEBIAN_FRONTEND=noninteractive apt-get update -q && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y tini;
COPY --from=api-builder /opt/openbas-build/openbas/openbas-api/target/openbas-api.jar ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openbas-api.jar"]
