FROM maven:3.8.4-openjdk-17 AS api-builder

WORKDIR /opt/openex-build/openex-api
COPY openex-api /opt/openex-build/openex-api
COPY openex-front/build /opt/openex-build/openex-front/build
RUN mvn install -DskipTests

FROM openjdk:17-slim AS app

RUN ln -s /usr/bin/dpkg-split /usr/sbin/dpkg-split
RUN ln -s /usr/bin/dpkg-deb /usr/sbin/dpkg-deb
RUN ln -s /bin/tar /usr/sbin/tar
RUN DEBIAN_FRONTEND=noninteractive apt-get update -q && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y tini;
COPY --from=api-builder /opt/openex-build/openex-api/target/openex-api.jar ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openex-api.jar"]
