FROM openjdk:21-jdk-slim AS app

WORKDIR /opt
RUN apt update && apt install -y tini git --no-install-recommends
COPY openex-build ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openex-api.jar"]