enum ReportInformationType {
  MAIN_INFORMATION = 'MAIN_INFORMATION',
  SCORE_DETAILS = 'SCORE_DETAILS',
  INJECT_RESULT = 'INJECT_RESULT',
  GLOBAL_OBSERVATION = 'GLOBAL_OBSERVATION',
  PLAYER_SURVEYS = 'PLAYER_SURVEYS',
  EXERCISE_DETAILS = 'EXERCISE_DETAILS',
}

export default ReportInformationType;
