package io.openbas.database.model;

public enum Capability {

  // Superuser
  BYPASS,

  // Atomic Testing
  ACCESS_ATOMIC_TESTING,
  MANAGE_ATOMIC_TESTING,
  DELETE_ATOMIC_TESTING,
  LAUNCH_ATOMIC_TESTING,

  // Simulation
  ACCESS_SIMULATION,
  MANAGE_SIMULATION,
  DELETE_SIMULATION,
  LAUNCH_SIMULATION,

  // Scenario
  ACCESS_SCENARIO,
  MANAGE_SCENARIO,
  DELETE_SCENARIO,
  LAUNCH_SCENARIO,

  // Teams & Players
  ACCESS_TEAMS_AND_PLAYERS,
  MANAGE_TEAMS_AND_PLAYERS,
  DELETE_TEAMS_AND_PLAYERS,
  MANAGE_ASSETS_FROM_TEAMS,
  DELETE_ASSETS_FROM_TEAMS,

  // Assets (Endpoints, Groups)
  ACCESS_ASSETS,
  MANAGE_ASSETS,
  DELETE_ASSETS,

  // Payloads
  ACCESS_PAYLOADS,
  MANAGE_PAYLOADS,
  DELETE_PAYLOADS,

  // Dashboards
  ACCESS_DASHBOARDS,
  MANAGE_DASHBOARDS,
  DELETE_DASHBOARDS,

  // Findings
  ACCESS_FINDINGS,
  MANAGE_FINDINGS,
  DELETE_FINDINGS,

  // Documents
  ACCESS_DOCUMENTS,
  MANAGE_DOCUMENTS,
  DELETE_DOCUMENTS,

  // Channels
  ACCESS_CHANNELS,
  MANAGE_CHANNELS,
  DELETE_CHANNELS,

  // Challenges
  ACCESS_CHALLENGES,
  MANAGE_CHALLENGES,
  DELETE_CHALLENGES,

  // Lessons Learned
  ACCESS_LESSONS_LEARNED,
  MANAGE_LESSONS_LEARNED,
  DELETE_LESSONS_LEARNED,

  // Security Platforms
  ACCESS_SECURITY_PLATFORMS,
  MANAGE_SECURITY_PLATFORMS,
  DELETE_SECURITY_PLATFORMS,

  // Platform Settings
  ACCESS_PLATFORM_SETTINGS,
  MANAGE_PLATFORM_SETTINGS;
}
