package io.openbas.database.model;

public enum ExecutionStatus {
  DRAFT,
  INFO,
  QUEUING,
  EXECUTING,
  PENDING,
  PARTIAL,
  ERROR,
  ERROR_ASSET_INACTIVE,
  WARNING,
  COMMAND_NOT_FOUND,
  COMMAND_CANNOT_BE_EXECUTED,
  MAYBE_PARTIAL_PREVENTED,
  MAYBE_PREVENTED,
  SUCCESS
}
