//region TOPBAR
export const APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED';
export const APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED';
//endregion

//region LOGIN / LOGOUT
export const APPLICATION_LOGIN_SUCCESS = 'APPLICATION_LOGIN_SUCCESS';
export const APPLICATION_LOGIN_SUBMITTED = 'APPLICATION_LOGIN_SUBMITTED';

export const APPLICATION_LOGOUT_ERROR = 'APPLICATION_LOGOUT_ERROR';
export const APPLICATION_LOGOUT_SUCCESS = 'APPLICATION_LOGOUT_SUCCESS';
export const APPLICATION_LOGOUT_SUBMITTED = 'APPLICATION_LOGOUT_SUBMITTED';
//endregion

//region EXERCISE_STATUSES
export const APPLICATION_FETCH_EXERCISE_STATUSES_SUBMITTED = 'APPLICATION_FETCH_EXERCISE_STATUSES_SUBMITTED';
export const APPLICATION_FETCH_EXERCISE_STATUSES_SUCCESS = 'APPLICATION_FETCH_EXERCISE_STATUSES_SUCCESS';
export const APPLICATION_FETCH_EXERCISE_STATUSES_ERROR = 'APPLICATION_FETCH_EXERCISE_STATUSES_ERROR';
//endregion

//region USERS
export const APPLICATION_FETCH_USERS_SUBMITTED = 'APPLICATION_FETCH_USERS_SUBMITTED';
export const APPLICATION_FETCH_USERS_SUCCESS = 'APPLICATION_FETCH_USERS_SUCCESS';
export const APPLICATION_FETCH_USERS_ERROR = 'APPLICATION_FETCH_USERS_ERROR';

export const APPLICATION_FETCH_USER_SUBMITTED = 'APPLICATION_FETCH_USER_SUBMITTED';
export const APPLICATION_FETCH_USER_SUCCESS = 'APPLICATION_FETCH_USER_SUCCESS';
export const APPLICATION_FETCH_USER_ERROR = 'APPLICATION_FETCH_USER_ERROR';
//endregion

//region EXERCISES
export const APPLICATION_FETCH_EXERCISES_SUBMITTED = 'APPLICATION_FETCH_EXERCISES_SUBMITTED';
export const APPLICATION_FETCH_EXERCISES_SUCCESS = 'APPLICATION_FETCH_EXERCISES_SUCCESS';
export const APPLICATION_FETCH_EXERCISES_ERROR = 'APPLICATION_FETCH_EXERCISES_ERROR';

export const APPLICATION_FETCH_EXERCISE_SUBMITTED = 'APPLICATION_FETCH_EXERCISE_SUBMITTED';
export const APPLICATION_FETCH_EXERCISE_SUCCESS = 'APPLICATION_FETCH_EXERCISE_SUCCESS';
export const APPLICATION_FETCH_EXERCISE_ERROR = 'APPLICATION_FETCH_EXERCISE_ERROR';

export const APPLICATION_ADD_EXERCISE_SUBMITTED = 'APPLICATION_ADD_EXERCISE_SUBMITTED';
export const APPLICATION_ADD_EXERCISE_SUCCESS = 'APPLICATION_ADD_EXERCISE_SUCCESS';
export const APPLICATION_ADD_EXERCISE_ERROR = 'APPLICATION_ADD_EXERCISE_ERROR';

export const APPLICATION_UPDATE_EXERCISE_SUBMITTED = 'APPLICATION_UPDATE_EXERCISE_SUBMITTED';
export const APPLICATION_UPDATE_EXERCISE_SUCCESS = 'APPLICATION_UPDATE_EXERCISE_SUCCESS';
export const APPLICATION_UPDATE_EXERCISE_ERROR = 'APPLICATION_UPDATE_EXERCISE_ERROR';
//endregion