//TEST
export const DATA_FETCH_SUBMITTED = 'DATA_FETCH_SUBMITTED';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_DELETE_SUCCESS = 'DATA_DELETE_SUCCESS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';

//region TOPBAR
export const APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED';
export const APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED';
//endregion

//region LOGIN / LOGOUT
export const IDENTITY_LOGIN_SUCCESS = 'IDENTITY_LOGIN_SUCCESS';
export const IDENTITY_LOGIN_SUBMITTED = 'IDENTITY_LOGIN_SUBMITTED';
export const IDENTITY_LOGOUT_ERROR = 'IDENTITY_LOGOUT_ERROR';
export const IDENTITY_LOGOUT_SUCCESS = 'IDENTITY_LOGOUT_SUCCESS';
export const IDENTITY_LOGOUT_SUBMITTED = 'IDENTITY_LOGOUT_SUBMITTED';
//endregion

//region AUDIENCE
export const APPLICATION_SELECT_AUDIENCE = 'APPLICATION_SELECT_AUDIENCE';
//endregion

//region INCIDENT
export const APPLICATION_SELECT_INCIDENT = 'APPLICATION_SELECT_INCIDENT';
//endregion

//region FILE
export const APPLICATION_FETCH_FILES_SUBMITTED = 'APPLICATION_FETCH_FILES_SUBMITTED';
export const APPLICATION_FETCH_FILES_SUCCESS = 'APPLICATION_FETCH_FILES_SUCCESS';
export const APPLICATION_FETCH_FILES_ERROR = 'APPLICATION_FETCH_FILES_ERROR';

export const APPLICATION_ADD_FILE_SUBMITTED = 'APPLICATION_ADD_FILE_SUBMITTED';
export const APPLICATION_ADD_FILE_SUCCESS = 'APPLICATION_ADD_FILE_SUCCESS';
export const APPLICATION_ADD_FILE_ERROR = 'APPLICATION_ADD_FILE_ERROR';
//endregion