//region TOPBAR
export const APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_LEFT_TOGGLE_SUBMITTED';
export const APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED = 'APPLICATION_NAVBAR_RIGHT_TOGGLE_SUBMITTED';
//endregion

//region LOGIN / LOGOUT
export const IDENTITY_LOGIN_SUCCESS = 'IDENTITY_LOGIN_SUCCESS';
export const IDENTITY_LOGIN_SUBMITTED = 'IDENTITY_LOGIN_SUBMITTED';
export const IDENTITY_LOGOUT_ERROR = 'IDENTITY_LOGOUT_ERROR';
export const IDENTITY_LOGOUT_SUCCESS = 'IDENTITY_LOGOUT_SUCCESS';
export const IDENTITY_LOGOUT_SUBMITTED = 'IDENTITY_LOGOUT_SUBMITTED';
//endregion

//region EXERCISE_STATUS
export const APPLICATION_FETCH_EXERCISE_STATUSES_SUBMITTED = 'APPLICATION_FETCH_EXERCISE_STATUSES_SUBMITTED';
export const APPLICATION_FETCH_EXERCISE_STATUSES_SUCCESS = 'APPLICATION_FETCH_EXERCISE_STATUSES_SUCCESS';
export const APPLICATION_FETCH_EXERCISE_STATUSES_ERROR = 'APPLICATION_FETCH_EXERCISE_STATUSES_ERROR';
//endregion

//region USER
export const APPLICATION_FETCH_USERS_SUBMITTED = 'APPLICATION_FETCH_USERS_SUBMITTED';
export const APPLICATION_FETCH_USERS_SUCCESS = 'APPLICATION_FETCH_USERS_SUCCESS';
export const APPLICATION_FETCH_USERS_ERROR = 'APPLICATION_FETCH_USERS_ERROR';

export const APPLICATION_FETCH_USER_SUBMITTED = 'APPLICATION_FETCH_USER_SUBMITTED';
export const APPLICATION_FETCH_USER_SUCCESS = 'APPLICATION_FETCH_USER_SUCCESS';
export const APPLICATION_FETCH_USER_ERROR = 'APPLICATION_FETCH_USER_ERROR';

export const APPLICATION_SEARCH_USERS_SUBMITTED = 'APPLICATION_SEARCH_USERS_SUBMITTED'

export const APPLICATION_ADD_USER_SUBMITTED = 'APPLICATION_ADD_USER_SUBMITTED';
export const APPLICATION_ADD_USER_SUCCESS = 'APPLICATION_ADD_USER_SUCCESS';
export const APPLICATION_ADD_USER_ERROR = 'APPLICATION_ADD_USER_ERROR';

export const APPLICATION_UPDATE_USER_SUBMITTED = 'APPLICATION_UPDATE_USER_SUBMITTED';
export const APPLICATION_UPDATE_USER_SUCCESS = 'APPLICATION_UPDATE_USER_SUCCESS';
export const APPLICATION_UPDATE_USER_ERROR = 'APPLICATION_UPDATE_USER_ERROR';

export const APPLICATION_DELETE_USER_SUBMITTED = 'APPLICATION_DELETE_USER_SUBMITTED';
export const APPLICATION_DELETE_USER_SUCCESS = 'APPLICATION_DELETE_USER_SUCCESS';
export const APPLICATION_DELETE_USER_ERROR = 'APPLICATION_DELETE_USER_ERROR';
//endregion

//region ORGANIZATION
export const APPLICATION_FETCH_ORGANIZATIONS_SUBMITTED = 'APPLICATION_FETCH_ORGANIZATIONS_SUBMITTED';
export const APPLICATION_FETCH_ORGANIZATIONS_SUCCESS = 'APPLICATION_FETCH_ORGANIZATIONS_SUCCESS';
export const APPLICATION_FETCH_ORGANIZATIONS_ERROR = 'APPLICATION_FETCH_ORGANIZATIONS_ERROR';

export const APPLICATION_FETCH_ORGANIZATION_SUBMITTED = 'APPLICATION_FETCH_ORGANIZATION_SUBMITTED';
export const APPLICATION_FETCH_ORGANIZATION_SUCCESS = 'APPLICATION_FETCH_ORGANIZATION_SUCCESS';
export const APPLICATION_FETCH_ORGANIZATION_ERROR = 'APPLICATION_FETCH_ORGANIZATION_ERROR';

export const APPLICATION_ADD_ORGANIZATION_SUBMITTED = 'APPLICATION_ADD_ORGANIZATION_SUBMITTED';
export const APPLICATION_ADD_ORGANIZATION_SUCCESS = 'APPLICATION_ADD_ORGANIZATION_SUCCESS';
export const APPLICATION_ADD_ORGANIZATION_ERROR = 'APPLICATION_ADD_ORGANIZATION_ERROR';

export const APPLICATION_UPDATE_ORGANIZATION_SUBMITTED = 'APPLICATION_UPDATE_ORGANIZATION_SUBMITTED';
export const APPLICATION_UPDATE_ORGANIZATION_SUCCESS = 'APPLICATION_UPDATE_ORGANIZATION_SUCCESS';
export const APPLICATION_UPDATE_ORGANIZATION_ERROR = 'APPLICATION_UPDATE_ORGANIZATION_ERROR';

export const APPLICATION_DELETE_ORGANIZATION_SUBMITTED = 'APPLICATION_DELETE_ORGANIZATION_SUBMITTED';
export const APPLICATION_DELETE_ORGANIZATION_SUCCESS = 'APPLICATION_DELETE_ORGANIZATION_SUCCESS';
export const APPLICATION_DELETE_ORGANIZATION_ERROR = 'APPLICATION_DELETE_ORGANIZATION_ERROR';
//endregion

//region EXERCISE
export const APPLICATION_FETCH_EXERCISES_SUBMITTED = 'APPLICATION_FETCH_EXERCISES_SUBMITTED';
export const APPLICATION_FETCH_EXERCISES_SUCCESS = 'APPLICATION_FETCH_EXERCISES_SUCCESS';
export const APPLICATION_FETCH_EXERCISES_ERROR = 'APPLICATION_FETCH_EXERCISES_ERROR';

export const APPLICATION_FETCH_EXERCISE_SUBMITTED = 'APPLICATION_FETCH_EXERCISE_SUBMITTED';
export const APPLICATION_FETCH_EXERCISE_SUCCESS = 'APPLICATION_FETCH_EXERCISE_SUCCESS';
export const APPLICATION_FETCH_EXERCISE_ERROR = 'APPLICATION_FETCH_EXERCISE_ERROR';

export const APPLICATION_ADD_EXERCISE_SUBMITTED = 'APPLICATION_ADD_EXERCISE_SUBMITTED';
export const APPLICATION_ADD_EXERCISE_SUCCESS = 'APPLICATION_ADD_EXERCISE_SUCCESS';
export const APPLICATION_ADD_EXERCISE_ERROR = 'APPLICATION_ADD_EXERCISE_ERROR';

export const APPLICATION_UPDATE_EXERCISE_SUBMITTED = 'APPLICATION_UPDATE_EXERCISE_SUBMITTED';
export const APPLICATION_UPDATE_EXERCISE_SUCCESS = 'APPLICATION_UPDATE_EXERCISE_SUCCESS';
export const APPLICATION_UPDATE_EXERCISE_ERROR = 'APPLICATION_UPDATE_EXERCISE_ERROR';

export const APPLICATION_DELETE_EXERCISE_SUBMITTED = 'APPLICATION_DELETE_EXERCISE_SUBMITTED';
export const APPLICATION_DELETE_EXERCISE_SUCCESS = 'APPLICATION_DELETE_EXERCISE_SUCCESS';
export const APPLICATION_DELETE_EXERCISE_ERROR = 'APPLICATION_DELETE_EXERCISE_ERROR';
//endregion

//region AUDIENCE
export const APPLICATION_FETCH_AUDIENCES_SUBMITTED = 'APPLICATION_FETCH_AUDIENCES_SUBMITTED';
export const APPLICATION_FETCH_AUDIENCES_SUCCESS = 'APPLICATION_FETCH_AUDIENCES_SUCCESS';
export const APPLICATION_FETCH_AUDIENCES_ERROR = 'APPLICATION_FETCH_AUDIENCES_ERROR';

export const APPLICATION_FETCH_AUDIENCE_SUBMITTED = 'APPLICATION_FETCH_AUDIENCE_SUBMITTED';
export const APPLICATION_FETCH_AUDIENCE_SUCCESS = 'APPLICATION_FETCH_AUDIENCE_SUCCESS';
export const APPLICATION_FETCH_AUDIENCE_ERROR = 'APPLICATION_FETCH_AUDIENCE_ERROR';

export const APPLICATION_ADD_AUDIENCE_SUBMITTED = 'APPLICATION_ADD_AUDIENCE_SUBMITTED';
export const APPLICATION_ADD_AUDIENCE_SUCCESS = 'APPLICATION_ADD_AUDIENCE_SUCCESS';
export const APPLICATION_ADD_AUDIENCE_ERROR = 'APPLICATION_ADD_AUDIENCE_ERROR';

export const APPLICATION_UPDATE_AUDIENCE_SUBMITTED = 'APPLICATION_UPDATE_AUDIENCE_SUBMITTED';
export const APPLICATION_UPDATE_AUDIENCE_SUCCESS = 'APPLICATION_UPDATE_AUDIENCE_SUCCESS';
export const APPLICATION_UPDATE_AUDIENCE_ERROR = 'APPLICATION_UPDATE_AUDIENCE_ERROR';

export const APPLICATION_DELETE_AUDIENCE_SUBMITTED = 'APPLICATION_DELETE_AUDIENCE_SUBMITTED';
export const APPLICATION_DELETE_AUDIENCE_SUCCESS = 'APPLICATION_DELETE_AUDIENCE_SUCCESS';
export const APPLICATION_DELETE_AUDIENCE_ERROR = 'APPLICATION_DELETE_AUDIENCE_ERROR';

export const APPLICATION_SELECT_AUDIENCE = 'APPLICATION_SELECT_AUDIENCE';
//endregion

//region EVENT
export const APPLICATION_FETCH_EVENTS_SUBMITTED = 'APPLICATION_FETCH_EVENTS_SUBMITTED';
export const APPLICATION_FETCH_EVENTS_SUCCESS = 'APPLICATION_FETCH_EVENTS_SUCCESS';
export const APPLICATION_FETCH_EVENTS_ERROR = 'APPLICATION_FETCH_EVENTS_ERROR';

export const APPLICATION_FETCH_EVENT_SUBMITTED = 'APPLICATION_FETCH_EVENT_SUBMITTED';
export const APPLICATION_FETCH_EVENT_SUCCESS = 'APPLICATION_FETCH_EVENT_SUCCESS';
export const APPLICATION_FETCH_EVENT_ERROR = 'APPLICATION_FETCH_EVENT_ERROR';

export const APPLICATION_ADD_EVENT_SUBMITTED = 'APPLICATION_ADD_EVENT_SUBMITTED';
export const APPLICATION_ADD_EVENT_SUCCESS = 'APPLICATION_ADD_EVENT_SUCCESS';
export const APPLICATION_ADD_EVENT_ERROR = 'APPLICATION_ADD_EVENT_ERROR';

export const APPLICATION_UPDATE_EVENT_SUBMITTED = 'APPLICATION_UPDATE_EVENT_SUBMITTED';
export const APPLICATION_UPDATE_EVENT_SUCCESS = 'APPLICATION_UPDATE_EVENT_SUCCESS';
export const APPLICATION_UPDATE_EVENT_ERROR = 'APPLICATION_UPDATE_EVENT_ERROR';

export const APPLICATION_DELETE_EVENT_SUBMITTED = 'APPLICATION_DELETE_EVENT_SUBMITTED';
export const APPLICATION_DELETE_EVENT_SUCCESS = 'APPLICATION_DELETE_EVENT_SUCCESS';
export const APPLICATION_DELETE_EVENT_ERROR = 'APPLICATION_DELETE_EVENT_ERROR';
//endregion

//region INCIDENT
export const APPLICATION_FETCH_ALL_INCIDENTS_SUBMITTED = 'APPLICATION_FETCH_ALL_INCIDENTS_SUBMITTED';
export const APPLICATION_FETCH_ALL_INCIDENTS_SUCCESS = 'APPLICATION_FETCH_ALL_INCIDENTS_SUCCESS';
export const APPLICATION_FETCH_ALL_INCIDENTS_ERROR = 'APPLICATION_FETCH_ALL_INCIDENTS_ERROR';

export const APPLICATION_FETCH_INCIDENTS_SUBMITTED = 'APPLICATION_FETCH_INCIDENTS_SUBMITTED';
export const APPLICATION_FETCH_INCIDENTS_SUCCESS = 'APPLICATION_FETCH_INCIDENTS_SUCCESS';
export const APPLICATION_FETCH_INCIDENTS_ERROR = 'APPLICATION_FETCH_INCIDENTS_ERROR';

export const APPLICATION_FETCH_INCIDENT_SUBMITTED = 'APPLICATION_FETCH_INCIDENT_SUBMITTED';
export const APPLICATION_FETCH_INCIDENT_SUCCESS = 'APPLICATION_FETCH_INCIDENT_SUCCESS';
export const APPLICATION_FETCH_INCIDENT_ERROR = 'APPLICATION_FETCH_INCIDENT_ERROR';

export const APPLICATION_ADD_INCIDENT_SUBMITTED = 'APPLICATION_ADD_INCIDENT_SUBMITTED';
export const APPLICATION_ADD_INCIDENT_SUCCESS = 'APPLICATION_ADD_INCIDENT_SUCCESS';
export const APPLICATION_ADD_INCIDENT_ERROR = 'APPLICATION_ADD_INCIDENT_ERROR';

export const APPLICATION_UPDATE_INCIDENT_SUBMITTED = 'APPLICATION_UPDATE_INCIDENT_SUBMITTED';
export const APPLICATION_UPDATE_INCIDENT_SUCCESS = 'APPLICATION_UPDATE_INCIDENT_SUCCESS';
export const APPLICATION_UPDATE_INCIDENT_ERROR = 'APPLICATION_UPDATE_INCIDENT_ERROR';

export const APPLICATION_DELETE_INCIDENT_SUBMITTED = 'APPLICATION_DELETE_INCIDENT_SUBMITTED';
export const APPLICATION_DELETE_INCIDENT_SUCCESS = 'APPLICATION_DELETE_INCIDENT_SUCCESS';
export const APPLICATION_DELETE_INCIDENT_ERROR = 'APPLICATION_DELETE_INCIDENT_ERROR';

export const APPLICATION_SELECT_INCIDENT = 'APPLICATION_SELECT_INCIDENT';
//endregion

//region INJECT
export const APPLICATION_FETCH_INJECTS_SUBMITTED = 'APPLICATION_FETCH_INJECTS_SUBMITTED';
export const APPLICATION_FETCH_INJECTS_SUCCESS = 'APPLICATION_FETCH_INJECTS_SUCCESS';
export const APPLICATION_FETCH_INJECTS_ERROR = 'APPLICATION_FETCH_INJECTS_ERROR';

export const APPLICATION_FETCH_INJECT_SUBMITTED = 'APPLICATION_FETCH_INJECT_SUBMITTED';
export const APPLICATION_FETCH_INJECT_SUCCESS = 'APPLICATION_FETCH_INJECT_SUCCESS';
export const APPLICATION_FETCH_INJECT_ERROR = 'APPLICATION_FETCH_INJECT_ERROR';

export const APPLICATION_ADD_INJECT_SUBMITTED = 'APPLICATION_ADD_INJECT_SUBMITTED';
export const APPLICATION_ADD_INJECT_SUCCESS = 'APPLICATION_ADD_INJECT_SUCCESS';
export const APPLICATION_ADD_INJECT_ERROR = 'APPLICATION_ADD_INJECT_ERROR';

export const APPLICATION_UPDATE_INJECT_SUBMITTED = 'APPLICATION_UPDATE_INJECT_SUBMITTED';
export const APPLICATION_UPDATE_INJECT_SUCCESS = 'APPLICATION_UPDATE_INJECT_SUCCESS';
export const APPLICATION_UPDATE_INJECT_ERROR = 'APPLICATION_UPDATE_INJECT_ERROR';

export const APPLICATION_DELETE_INJECT_SUBMITTED = 'APPLICATION_DELETE_INJECT_SUBMITTED';
export const APPLICATION_DELETE_INJECT_SUCCESS = 'APPLICATION_DELETE_INJECT_SUCCESS';
export const APPLICATION_DELETE_INJECT_ERROR = 'APPLICATION_DELETE_INJECT_ERROR';
//endregion

//region FILE
export const APPLICATION_FETCH_FILES_SUBMITTED = 'APPLICATION_FETCH_FILES_SUBMITTED';
export const APPLICATION_FETCH_FILES_SUCCESS = 'APPLICATION_FETCH_FILES_SUCCESS';
export const APPLICATION_FETCH_FILES_ERROR = 'APPLICATION_FETCH_FILES_ERROR';

export const APPLICATION_ADD_FILE_SUBMITTED = 'APPLICATION_ADD_FILE_SUBMITTED';
export const APPLICATION_ADD_FILE_SUCCESS = 'APPLICATION_ADD_FILE_SUCCESS';
export const APPLICATION_ADD_FILE_ERROR = 'APPLICATION_ADD_FILE_ERROR';
//endregion