//region AVATAR
export const AVATAR_TYPE_TOPBAR = 'AVATAR_TYPE_TOPBAR'
export const AVATAR_TYPE_LIST = 'AVATAR_TYPE_LIST'
export const AVATAR_TYPE_MAINLIST = 'AVATAR_TYPE_MAINLIST'
export const AVATAR_TYPE_CHIP = 'AVATAR_TYPE_CHIP'
//endregion

// region LISTITEM
export const LIST_ITEM_NOSPACE = 'LIST_ITEM_NOSPACE'
//endregion

//region ICON
export const ICON_TYPE_NAVBAR = 'ICON_TYPE_NAVBAR'
export const ICON_TYPE_LIST = 'ICON_TYPE_LIST'
export const ICON_TYPE_LEFT = 'ICON_TYPE_LEFT'
export const ICON_TYPE_MAINLIST = 'ICON_TYPE_MAINLIST'
export const ICON_TYPE_MAINLIST2 = 'ICON_TYPE_MAINLIST2'
export const ICON_TYPE_MAINLIST_RIGHT = 'ICON_TYPE_MAINLIST_RIGHT'
export const ICON_TYPE_SORT = 'ICON_TYPE_SORT'

export const ICON_NAME_LOCAL_MOVIES = 'ICON_NAME_LOCAL_MOVIES'
export const ICON_NAME_HARDWARE_COMPUTER = 'ICON_NAME_HARDWARE_COMPUTER'
export const ICON_NAME_SOCIAL_PERSON = 'ICON_NAME_SOCIAL_PERSON'
export const ICON_NAME_SOCIAL_GROUP = 'ICON_NAME_SOCIAL_GROUP'
export const ICON_NAME_SOCIAL_PUBLIC = 'ICON_NAME_SOCIAL_PUBLIC'
export const ICON_NAME_CONTENT_ADD = 'ICON_NAME_CONTENT_ADD'
export const ICON_NAME_CONTENT_MAIL = 'ICON_NAME_CONTENT_MAIL'
export const ICON_NAME_CONTENT_FLAG = 'ICON_NAME_CONTENT_FLAG'
export const ICON_NAME_CONTENT_COPY = 'ICON_NAME_CONTENT_COPY'
export const ICON_NAME_CONTENT_REMOVE_CIRCLE = 'ICON_NAME_CONTENT_REMOVE_CIRCLE'
export const ICON_NAME_ACTION_DELETE = 'ICON_NAME_ACTION_DELETE'
export const ICON_NAME_ACTION_SETTINGS = 'ICON_NAME_ACTION_SETTINGS'
export const ICON_NAME_ACTION_SCHEDULE = 'ICON_NAME_ACTION_SCHEDULE'
export const ICON_NAME_ACTION_EVENT = 'ICON_NAME_ACTION_EVENT'
export const ICON_NAME_ACTION_EXIT_TO_APP = 'ICON_NAME_ACTION_EXIT_TO_APP'
export const ICON_NAME_ACTION_CHECK_CIRCLE = 'ICON_NAME_ACTION_CHECK_CIRCLE'
export const ICON_NAME_ACTION_ASSIGNMENT_TURNED_IN = 'ICON_NAME_ACTION_ASSIGNMENT_TURNED_IN'
export const ICON_NAME_ACTION_DONE = 'ICON_NAME_ACTION_DONE'
export const ICON_NAME_ACTION_DONE_ALL = 'ICON_NAME_ACTION_DONE_ALL'
export const ICON_NAME_NAVIGATION_MORE_VERT = 'ICON_NAME_NAVIGATION_MORE_VERT'
export const ICON_NAME_NAVIGATION_ARROW_DROP_DOWN = 'ICON_NAME_NAVIGATION_ARROW_DROP_DOWN'
export const ICON_NAME_NAVIGATION_ARROW_DROP_UP = 'ICON_NAME_NAVIGATION_ARROW_DROP_UP'
export const ICON_NAME_NAVIGATION_CANCEL = 'ICON_NAME_NAVIGATION_CANCEL'
export const ICON_NAME_FILE_FOLDER = 'ICON_NAME_FILE_FOLDER'
export const ICON_NAME_EDITOR_ATTACH_FILE = 'ICON_NAME_EDITOR_ATTACH_FILE'
export const ICON_NAME_EDITOR_INSERT_CHART = 'ICON_NAME_EDITOR_INSERT_CHART'
export const ICON_NAME_MAPS_LAYERS = 'ICON_NAME_MAPS_LAYERS'
export const ICON_NAME_NOTIFICATION_SMS = 'ICON_NAME_NOTIFICATION_SMS'
export const ICON_NAME_NOTIFICATION_NETWORK_CHECK = 'ICON_NAME_NOTIFICATION_NETWORK_CHECK'
export const ICON_NAME_NOTIFICATION_ONDEMAND_VIDEO = 'ICON_NAME_NOTIFICATION_ONDEMAND_VIDEO'
export const ICON_NAME_IMAGE_CENTER_FOCUS_STRONG = 'ICON_NAME_IMAGE_CENTER_FOCUS_STRONG'
export const ICON_NAME_IMAGE_CENTER_FOCUS_WEAK = 'ICON_NAME_IMAGE_CENTER_FOCUS_WEAK'
export const ICON_NAME_AV_PLAY_CIRCLE_OUTLINE = 'ICON_NAME_AV_PLAY_CIRCLE_OUTLINE'
export const ICON_NAME_AV_PLAY_ARROW = 'ICON_NAME_AV_PLAY_ARROW'
export const ICON_NAME_AV_SLOW_MOTION_VIDEO = 'ICON_NAME_AV_SLOW_MOTION_VIDEO'
export const ICON_NAME_DEVICE_GRAPHIC_EQ = 'ICON_NAME_DEVICE_GRAPHIC_EQ'
//endregion

//region BUTTON
export const BUTTON_TYPE_FLOATING = 'BUTTON_TYPE_FLOATING'
export const BUTTON_TYPE_FLOATING_PADDING = 'BUTTON_TYPE_FLOATING_PADDING'
export const BUTTON_TYPE_DIALOG_LEFT = 'BUTTON_TYPE_DIALOG_LEFT'
export const BUTTON_TYPE_CREATE_RIGHT = 'BUTTON_TYPE_CREATE_RIGHT'
//endregion

//region APPBAR
export const APPBAR_TYPE_TOPBAR_NOICON = 'APPBAR_TYPE_TOPBAR_NOICON'
export const APPBAR_TYPE_TOPBAR = 'APPBAR_TYPE_TOPBAR'
export const APPBAR_TYPE_LEFTBAR = 'APPBAR_TYPE_LEFTBAR'
//endregion

//region TOOLBAR
export const TOOLBAR_TYPE_LOGIN = 'TOOLBAR_TYPE_LOGIN'
export const TOOLBAR_TYPE_EVENT = 'TOOLBAR_TYPE_EVENT'
//endregion

//region PAPER
export const PAPER_TYPE_EXERCISE = 'PAPER_TYPE_EXERCISE'
export const PAPER_TYPE_EVENT = 'PAPER_TYPE_EVENT'
export const PAPER_TYPE_SETTINGS = 'PAPER_TYPE_SETTINGS'
//endregion

//region CHIP
export const CHIP_TYPE_FLOATING = 'CHIP_TYPE_FLOATING'
export const CHIP_TYPE_LIST = 'CHIP_TYPE_LIST'
//endregion

//region GRIDLIST
export const GRIDLIST_TYPE_GALLERY = 'GRIDLIST_TYPE_GALLERY'
//endregion

//region SNACKBAR
export const SNACKBAR_TYPE_LOADING = 'SNACKBAR_TYPE_LOADING'
//endregion

//region FIELD
export const FIELD_TYPE_INTITLE = 'FIELD_TYPE_INTITLE'
export const FIELD_TYPE_INLINE = 'FIELD_TYPE_INLINE'
export const FIELD_TYPE_RIGHT = 'FIELD_TYPE_RIGHT'
//endregion

//region SPINNER
export const SPINNER_TYPE_NAV = 'SPINNER_TYPE_NAV'