//region AVATAR
export const AVATAR_TYPE_TOPBAR = 'AVATAR_TYPE_TOPBAR';
export const AVATAR_TYPE_LIST = 'AVATAR_TYPE_LIST';
//endregion

//region ICON
export const ICON_TYPE_NAVBAR = 'ICON_TYPE_NAVBAR';
export const ICON_TYPE_LIST = 'ICON_TYPE_LIST';

export const ICON_NAME_LOCAL_MOVIES = 'ICON_NAME_LOCAL_MOVIES';
export const ICON_NAME_HARDWARE_COMPUTER = 'ICON_NAME_HARDWARE_COMPUTER';
export const ICON_NAME_SOCIAL_PERSON = 'ICON_NAME_SOCIAL_PERSON';
export const ICON_NAME_SOCIAL_GROUP = 'ICON_NAME_SOCIAL_GROUP';
export const ICON_NAME_SOCIAL_PUBLIC = 'ICON_NAME_SOCIAL_PUBLIC';
export const ICON_NAME_CONTENT_ADD = 'ICON_NAME_CONTENT_ADD';
export const ICON_NAME_CONTENT_MAIL = 'ICON_NAME_CONTENT_MAIL';
export const ICON_NAME_CONTENT_FLAG = 'ICON_NAME_CONTENT_FLAG';
export const ICON_NAME_CONTENT_COPY = 'ICON_NAME_CONTENT_COPY';
export const ICON_NAME_ACTION_DELETE = 'ICON_NAME_ACTION_DELETE';
export const ICON_NAME_ACTION_SETTINGS = 'ICON_NAME_ACTION_SETTINGS';
export const ICON_NAME_ACTION_SCHEDULE = 'ICON_NAME_ACTION_SCHEDULE';
export const ICON_NAME_ACTION_EVENT = 'ICON_NAME_ACTION_EVENT';
export const ICON_NAME_ACTION_EXIT_TO_APP = 'ICON_NAME_ACTION_EXIT_TO_APP';
export const ICON_NAME_ACTION_ASSIGNMENT_TURNED_IN = 'ICON_NAME_ACTION_ASSIGNMENT_TURNED_IN';
export const ICON_NAME_NAVIGATION_MORE_VERT = 'ICON_NAME_NAVIGATION_MORE_VERT';
export const ICON_NAME_FILE_FOLDER = 'ICON_NAME_FILE_FOLDER';
export const ICON_NAME_EDITOR_ATTACH_FILE = 'ICON_NAME_EDITOR_ATTACH_FILE';
//endregion

//region BUTTON
export const BUTTON_TYPE_FLOATING = 'BUTTON_TYPE_FLOATING';
export const BUTTON_TYPE_FLOATING_PADDING = 'BUTTON_TYPE_FLOATING_PADDING';
//endregion

//region APPBAR
export const APPBAR_TYPE_TOPBAR_NOICON = 'APPBAR_TYPE_TOPBAR_NOICON';
export const APPBAR_TYPE_TOPBAR = 'APPBAR_TYPE_TOPBAR';
export const APPBAR_TYPE_LEFTBAR = 'APPBAR_TYPE_LEFTBAR';
//endregion

//region TOOLBAR
export const TOOLBAR_TYPE_LOGIN = 'TOOLBAR_TYPE_LOGIN';
//endregion

//region PAPER
export const PAPER_TYPE_EXERCISE = 'PAPER_TYPE_EXERCISE';
export const PAPER_TYPE_SETTINGS = 'PAPER_TYPE_SETTINGS';
//endregion

//region CHIP
export const CHIP_TYPE_FLOATING = 'CHIP_TYPE_FLOATING';
export const CHIP_TYPE_LIST = 'CHIP_TYPE_LIST';
//endregion

//region GRIDLIST
export const GRIDLIST_TYPE_GALLERY = 'GRIDLIST_TYPE_GALLERY';
//endregion

//region SNACKBAR
export const SNACKBAR_TYPE_LOADING = 'SNACKBAR_TYPE_LOADING';
//endregion
