// DATA
export const DATA_FETCH_SUBMITTED = 'DATA_FETCH_SUBMITTED';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_DELETE_SUCCESS = 'DATA_DELETE_SUCCESS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';
export const DATA_UPDATE_SUCCESS = 'DATA_UPDATE_SUCCESS';
export const DATA_SAVED_DISMISS = 'DATA_SAVED_DISMISS';

// region WORKER
export const DATA_FETCH_WORKER_STATUS = 'DATA_FETCH_WORKER_STATUS';
// endregion

// region TOPBAR
export const APPLICATION_NAVBAR_LEFT_TOGGLE_UNFOLDING = 'APPLICATION_NAVBAR_LEFT_TOGGLE_UNFOLDING';
export const APPLICATION_NAVBAR_LEFT_TOGGLE_CONFIGURATION = 'APPLICATION_NAVBAR_LEFT_TOGGLE_CONFIGURATION';
// endregion

// region LOGIN / LOGOUT
export const IDENTITY_LOGIN_SUCCESS = 'IDENTITY_LOGIN_SUCCESS';
export const IDENTITY_LOGIN_FAILED = 'IDENTITY_LOGIN_FAILED';
export const IDENTITY_LOGOUT_SUCCESS = 'IDENTITY_LOGOUT_SUCCESS';
// endregion

// region lang
export const LANG_UPDATE_ON_USER_CHANGE = 'LANG_UPDATE_ON_USER_CHANGE';
// endregion
