<?php
namespace App\Constant;

class ExerciseConstantClass
{
    const CST_EXERCISE = 'exercise';
    const CST_AUDIENCE = 'audience';
    const CST_OBJECTIVE = 'objective';
    const CST_SCENARIOS = 'scenarios';
    const CST_INJECTS = 'injects';
    const CST_INCIDENTS = 'incidents';

    // Constantes Import/Export Exercise
    const CST_EXERCISE_ID = 'EXERCISE_ID';
    const CST_EXERCISE_OWNER = 'EXERCISE_OWNER';
    const CST_EXERCISE_IMAGE = 'EXERCISE_IMAGE';
    const CST_EXERCISE_ANIMATION_GROUP = 'EXERCISE_ANIMATION_GROUP';
    const CST_EXERCISE_NAME = 'EXERCISE_NAME';
    const CST_EXERCISE_SUBTITLE = 'EXERCISE_SUBTITLE';
    const CST_EXERCISE_DESCRIPTION = 'EXERCISE_DESCRIPTION';
    const CST_EXERCISE_START_DATE = 'EXERCISE_START_DATE';
    const CST_EXERCISE_END_DATE = 'EXERCISE_END_DATE';
    const CST_EXERCISE_MESSAGE_HEADER = 'EXERCISE_MESSAGE_HEADER';
    const CST_EXERCISE_MESSAGE_FOOTER = 'EXERCISE_MESSAGE_FOOTER';
    const CST_EXERCISE_CANCELED = 'EXERCISE_CANCELED';
    const CST_EXERCISE_MAIL_EXPEDITEUR = 'EXERCISE_MAIL_EXPEDITEUR';

    // Audience
    const CST_AUDIENCE_ID = 'AUDIENCE_ID';
    const CST_AUDIENCE_NAME = 'AUDIENCE_NAME';
    const CST_AUDIENCE_ENABLED = 'AUDIENCE_ENABLED';

    // Sub Audience
    const CST_SUBAUDIENCE_ID = 'SUBAUDIENCE_ID';
    const CST_SUBAUDIENCE_NAME = 'SUBAUDIENCE_NAME';
    const CST_SUBAUDIENCE_ENABLED = 'SUBAUDIENCE_ENABLED';

    // User
    const CST_USER_ID = 'USER_ID';
    const CST_USER_ORGANIZATION = 'USER_ORGANIZATION';
    const CST_USER_LOGIN = 'USER_LOGIN';
    const CST_USER_FIRSTNAME = 'USER_FIRSTNAME';
    const CST_USER_LASTNAME = 'USER_LASTNAME';
    const CST_USER_EMAIL = 'USER_EMAIL';
    const CST_USER_EMAIL2 = 'USER_EMAIL2';
    const CST_USER_PHONE = 'USER_PHONE';
    const CST_USER_PHONE2 = 'USER_PHONE2';
    const CST_USER_PHONE3 = 'USER_PHONE3';
    const CST_USER_ADMIN = 'USER_ADMIN';
    const CST_USER_STATUS = 'USER_STATUS';
    const CST_USER_PASSWORD = 'USER_PASSWORD';

    // Objective Data
    const CST_OBJECTIVE_ID = 'OBJECTIVE_ID';
    const CST_OBJECTIVE_TITLE = 'OBJECTIVE_TITLE';
    const CST_OBJECTIVE_DESCRIPTION = 'OBJECTIVE_DESCRIPTION';
    const CST_OBJECTIVE_PRIORITY = 'OBJECTIVE_PRIORITY';
    const CST_SUBOBJECTIVE_ID = 'SUBOBJECTIVE_ID';
    const CST_SUBOBJECTIVE_TITLE = 'SUBOBJECTIVE_TITLE';
    const CST_SUBOBJECTIVE_DESCRIPTION = 'SUBOBJECTIVE_DESCRIPTION';
    const CST_SUBOBJECTIVE_PRIORITY = 'SUBOBJECTIVE_PRIORITY';

    // Scenarios Data
    const CST_EVENT_ID = 'EVENT_ID';
    const CST_EVENT_IMAGE = 'EVENT_IMAGE';
    const CST_EVENT_TITLE = 'EVENT_TITLE';
    const CST_EVENT_DESCRIPTION = 'EVENT_DESCRIPTION';
    const CST_EVENT_ORDER = 'EVENT_ORDER';

    // Incident Data
    const CST_INCIDENT_ID = 'INCIDENT_ID';
    const CST_INCIDENT_TYPE = 'INCIDENT_TYPE';
    const CST_INCIDENT_EVENT = 'INCIDENT_EVENT';
    const CST_INCIDENT_TITLE = 'INCIDENT_TITLE';
    const CST_INCIDENT_STORY = 'INCIDENT_STORY';
    const CST_INCIDENT_WEIGHT = 'INCIDENT_WEIGHT';
    const CST_INCIDENT_ORDER = 'INCIDENT_ORDER';
    const CST_INCIDENT_OUTCOME_COMMENT = 'INCIDENT_OUTCOME_COMMENT';
    const CST_INCIDENT_OUTCOME_RESULT = 'INCIDENT_OUTCOME_RESULT';

    // Injects Data
    const CST_INJECT_ID = 'INJECT_ID';
    const CST_INJECT_INCIDENT_ID = 'INJECT_INCIDENT_ID';
    const CST_INJECT_USER = 'INJECT_USER';
    const CST_INJECT_TITLE = 'INJECT_TITLE';
    const CST_INJECT_DESCRIPTION = 'INJECT_DESCRIPTION';
    const CST_INJECT_CONTENT = 'INJECT_CONTENT';
    const CST_INJECT_TYPE = 'INJECT_TYPE';
    const CST_INJECT_ALL_AUDIENCES = 'INJECT_ALL_AUDIENCES';
    const CST_INJECT_AUDIENCES = 'INJECT_AUDIENCES';
    const CST_INJECT_SUBAUDIENCES = 'INJECT_SUBAUDIENCES';
    const CST_INJECT_ENABLED = 'INJECT_ENABLED';
    const CST_INJECT_DATE = 'INJECT_DATE';
    const CST_INJECT_STATUS_NAME = 'INJECT_STATUS_NAME';
    const CST_INJECT_STATUS_MESSAGE = 'INJECT_STATUS_MESSAGE';
    const CST_INJECT_STATUS_DATE = 'INJECT_STATUS_DATE';
    const CST_INJECT_STATUS_EXECUTION = 'INJECT_STATUS_EXECUTION';
}
