<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.openaev</groupId>
        <artifactId>openaev-platform</artifactId>
        <version>3.260904.0</version>
    </parent>

    <artifactId>openaev-build-services</artifactId>
    <name>OpenAEV Build Services</name>
    <description>Compile-time services for OpenAEV</description>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.6.2</version>
        </dependency>
    </dependencies>
</project>
