package io.openaev.ocsf.schema.v190.objects;

import io.openaev.ocsf.schema.OcsfObject;

@lombok.Getter
public class OcsfObjectDelegation extends OcsfObject {
  /** The time when the delegation was issued by the issuing authority. */
  @com.fasterxml.jackson.annotation.JsonProperty(value = "created_time_dt")
  private io.openaev.ocsf.schema.v190.datatypes.OcsfDatatypeDatetimeT createdTimeDtField;

  /** The time when the delegation was issued by the issuing authority. */
  @com.fasterxml.jackson.annotation.JsonProperty(value = "created_time")
  private io.openaev.ocsf.schema.v190.datatypes.OcsfDatatypeTimestampT createdTimeField;

  /**
   * The unique identifier of the trusted issuing authority (e.g., an OAuth authorization server,
   * cloud STS, IAM broker, orchestration gateway, or SDK wrapper) that generated this delegation.
   * Enables verification that delegation IDs were issued by an authorized component rather than
   * self-asserted by the delegate.
   */
  @com.fasterxml.jackson.annotation.JsonProperty(value = "issuer_uid")
  private io.openaev.ocsf.schema.v190.datatypes.OcsfDatatypeStringT issuerUidField;

  /**
   * The delegation identifier of the parent delegation, if this delegation was created by
   * re-delegating authority to another party (e.g., a downstream service or automated process).
   * This creates a parent-child relationship that enables tracking the complete chain of delegation
   * ancestry. Does not indicate that the delegate was instantiated or spawned by the parent's
   * delegate; that relationship, if any, is tracked separately.
   */
  @com.fasterxml.jackson.annotation.JsonProperty(value = "parent_uid")
  private io.openaev.ocsf.schema.v190.datatypes.OcsfDatatypeStringT parentUidField;

  /**
   * Unique identifier for this delegation context. Must be stable across the lifetime of the
   * delegation and generated by a trusted issuing authority (e.g., an OAuth authorization server,
   * cloud STS, IAM broker, or orchestration gateway) rather than self-asserted by the delegate. All
   * events executed under this delegation share this identifier.
   */
  @com.fasterxml.jackson.annotation.JsonProperty(value = "uid")
  private io.openaev.ocsf.schema.v190.datatypes.OcsfDatatypeStringT uidField;
}
