/* eslint-disable no-template-curly-in-string */

const i18n = {
  messages: {
    fr: {
      'Email address': 'Adresse email',
      Password: 'Mot de passe',
      'Password validation': 'Validation du mot de passe',
      'Change your password': 'Changer votre mot de passe',
      'I forgot my password': "J'ai oublié mon mot de passe",
      'Send reset code': 'Envoyer le code',
      'Enter code': 'Entrer le code',
      'Back to login': "Retour à l'identification",
      'Sign in': "S'identifier",
      'Login with github': "S'identifier avec github",
      'You probably need a public email in your github account':
        "Vous avez probablement besoin d'une adresse e-mail publique dans votre compte github",
      'Should be a valid email address': 'Doit être une adresse e-mail valide',
      'Login with microsoft': "S'identifier avec microsoft",
      Continue: 'Continuer',
      Dashboard: 'Tableau de bord',
      Players: 'Joueurs',
      Organizations: 'Organisations',
      Documents: 'Documents',
      Integrations: 'Intégrations',
      Settings: 'Paramètres',
      Profile: 'Profil',
      Logout: 'Se déconnecter',
      Firstname: 'Prénom',
      Lastname: 'Nom de famille',
      Organization: 'Organisation',
      Language: 'Langue',
      Injects: 'Stimulis',
      Messages: 'Messages',
      Mails: 'Mails',
      Timeline: 'Chronologie',
      Definition: 'Définition',
      Results: 'Résultats',
      Channels: 'Canaux',
      Submit: 'Soumettre',
      Country: 'Pays',
      Flag: 'Flag',
      Flags: 'Flags',
      'Flag type': 'Type de flag',
      'Flag is correct! It has been successfully submitted.':
        'Le flag est correct! Il a été soumis avec succès.',
      'Flag is not correct! Try again...':
        'Le flag est incorrect! Merci de rééssayer...',
      'Preview challenges page': 'Aperçu des challenges',
      'Switch to preview mode': 'Basculer en mode aperçu',
      'Switch to player mode': 'Basculer en mode joueur',
      'Create a new channel': 'Créer un nouveau canal',
      'Update the channel': 'Modifier le canal',
      'Recent simulations': 'Simulations récents',
      'No teams.': 'Aucune équipe.',
      'No simulations in this platform.': 'Aucune simulations dans cette plateforme.',
      'Injects distribution': 'Distribution des stimulis',
      'Next injects to send': 'Prochains stimlis à envoyer',
      'Organizations distribution across simulations':
        'Distribution des organisations dans les simulations',
      'Players distribution': 'Distribution des joueurs',
      'Inject context': 'Contexte du stimuli',
      'added an entry on': 'a ajouté une entrée le',
      'This file type is not accepted here.':
        "Ce type de fichier n'est pas accepté ici",
      'Distribution of score by team (in % of expectations)':
        'Distribution du score par team (en % des attendus)',
      'Select all': 'Sélectionner tout',
      'Do you want to anonymize lessons learned questionnaire?':
        "Souhaitez-vous anonymiser le questionnaire de retour d'expérience ?",
      'You will not be able to change this setting later.':
        'Vous ne serez plus en mesure de modifier ce paramètre après.',
      'Search these results': 'Rechercher ces résultats',
      Stop: 'Arrêter',
      Name: 'Nom',
      Subtitle: 'Sous-titre',
      'Please note that if you change the “Reply to” address, the email interaction functionality in the platform will be disabled.': 'Veuillez noter que si vous modifiez l\'adresse « Répondre à », la fonctionnalité d\'interaction par mail dans la plateforme sera désactivée.',
      'Start date': 'Date de début',
      'End date': 'Date de fin',
      To: 'A',
      From: 'De',
      'Reply to': 'Répondre à',
      Tags: 'Tags',
      Reply: 'Répondre',
      newspaper: 'Journal',
      tv: 'Chaîne de télévision',
      Anonymize: 'Anonymiser',
      microblogging: 'Microblogging',
      'Targeted players': 'Joueurs ciblés',
      'Inject details': 'Détails du stimuli',
      'Export injects': 'Exporter les stimulis',
      'Create a new simulation': 'Créer une nouvelle simulation',
      'Create a new scenario': 'Créer un nouveau scenario',
      'Do you want to delete this team?':
        'Souhaitez-vous supprimer cette team ?',
      'Do you want to delete this comcheck?':
        'Souhaitez-vous supprimer cette vérification ?',
      'Do you want to delete this player?':
        'Souhaitez-vous supprimer ce joueur ?',
      'Do you want to delete this inject?':
        'Souhaitez-vous supprimer ce stimuli ?',
      'Do you want to delete these {count} injects?':
        'Souhaitez-vous supprimer ces {count} stimulis ?',
      'Do you want to delete this channel?':
        'Souhaitez-vous supprimer ce canal ?',
      'Start date (optional)': 'Date de début (optionnel)',
      'Create a new player': 'Créer un nouveau joueur',
      'Update the player': 'Modifier le joueur',
      'one month': 'un mois',
      'Phone number (mobile)': 'Numéro de téléphone (mobile)',
      'Phone number (landline)': 'Numéro de téléphone (fixe)',
      'PGP public key': 'Clé publique PGP',
      'Create a new organization': 'Créer une nouvelle organisation',
      'Update the organization': "Modifier l'organisation",
      'Do you want to delete this organization?':
        'Souhaitez-vous supprimer cette organisation ?',
      'Mail sent to': 'Mail envoyé à',
      'Teams scores over time (in % of expectations)':
        'Score des team dans le temps (en % des attendus)',
      'Distribution of total score by inject type':
        'Distribution du score total par type de stimuli',
      on: 'le',
      Manual: 'Manuel',
      'Total score': 'Score total',
      Parameters: 'Configuration',
      'Default theme': 'Thème par défaut',
      'Default language': 'Langue par défaut',
      'Background color': 'Couleur d\'arrière plan',
      'Paper color': 'Couleur du papier',
      'Navigation color': 'Couleur de navigation',
      'Primary color': 'Couleur primaire',
      'Secondary color': 'Couleur secondaire',
      'Accent color': 'Couleur d\'accentuation',
      'Logo URL': 'URL du logo',
      'Logo URL (collapsed)': 'URL du logo (réduit)',
      'Logo URL (login)': 'URL du logo (login)',
      'Do you want to trigger this inject now?':
        'Souhaitez-vous déclencher ce stimuli maintenant ?',
      Administrator: 'Administrateur',
      'Trigger now': 'Déclencher maintenant',
      Automatic: 'Automatique',
      'Passwords do no match': 'Les mots de passe ne correspondent pas',
      'Update the user password': "Modifier le mot de passe de l'utilisateur",
      'Update password': 'Modifier le mot de passe',
      'Current password': 'Mot de passe actuel',
      'New password': 'Nouveau mot de passe',
      Security: 'Sécurité',
      Users: 'Utilisateurs',
      Groups: 'Groupes',
      'Create a new group': 'Créer un groupe',
      'Create a new tag': 'Créer un nouveau tag',
      'Do you want to delete this tag?': 'Souhaitez-vous supprimer ce tag ?',
      'Update the tag': 'Modifier le tag',
      'Manage grants': 'Gérer les permissions',
      'Manage users': 'Gérer les utilisateurs',
      'Manage players': 'Gérer les joueurs',
      'Do you want to delete this user?':
        'Souhaitez-vous supprimer cet utilisateur ?',
      'Do you want to delete this group?':
        'Souhaitez-vous supprimer ce groupe ?',
      'No tag': 'Aucun tag',
      'Update the user': "Modifier l'utilisateur",
      'Read/Write': 'Lecture/Ecriture',
      'Read Only': 'Lecture Seule',
      'Update the group': 'Modifier le groupe',
      Value: 'Valeur',
      Color: 'Couleur',
      Cancel: 'Annuler',
      Back: 'Retour',
      Next: 'Suivant',
      Create: 'Créer',
      Launch: 'Lancer',
      Update: 'Modifier',
      Duplicate: 'Dupliquer',
      'Do you want to duplicate this scenario:': 'Voulez-vous dupliquer ce scénario : ',
      'Do you want to delete this scenario:': 'Voulez-vous supprimer ce scénario : ',
      'Do you want to duplicate this simulation:': 'Voulez-vous dupliquer cette simulation : ',
      'Do you want to delete this simulation:': 'Voulez-vous supprimer cette simulation : ',
      'Do you want to duplicate this atomic testing:': 'Voulez-vous dupliquer cet atomic testing : ',
      'Do you want to delete this atomic testing:': 'Voulez-vous supprimer cet atomic testing : ',
      'Do you want to duplicate this inject:': 'Voulez-vous dupliquer ce stimuli : ',
      Delete: 'Supprimer',
      Edition: 'Edition',
      Confirmation: 'Confirmation',
      Search: 'Rechercher',
      Required: 'Obligatoire',
      'Technical targets': 'Cibles techniques',
      'Platform name': 'Nom de la plateforme',
      'Components version': 'Version des composants',
      'Sent at': 'Envoyé le',
      'Mails not read': 'Mails non lus',
      'Total mails': 'Mails totaux',
      Dark: 'Sombre',
      Light: 'Clair',
      'This field is required.': 'Ce champ est requis.',
      'The element has been updated': "L'élément a été modifié.",
      'The element already exists': "L'élément existe déjà.",
      'Manage the users of this group': 'Gérer les utilisateurs de ce groupe',
      'Create a new document': 'Créer un nouveau document',
      Close: 'Fermer',
      'Export to XLS': 'Exporter en XLS',
      'Export to image': 'Exporter en image',
      'Export to PDF': 'Exporter en PDF',
      'Export to CSV': 'Exporter en CSV',
      Copy: 'Copier',
      Start: 'Démarrer',
      'Start now': 'Démarrer maintenant',
      Status: 'Statut',
      Information: 'Information',
      Control: 'Contrôle',
      Scheduled: 'Planifié',
      Finished: 'Terminé',
      Execution: 'Exécution',
      Dryrun: 'Simulation',
      Comcheck: 'Vérification',
      Send: 'Envoyer',
      Remove: 'Retirer',
      Add: 'Ajouter',
      Scenario: 'Scénario',
      Title: 'Titre',
      Enabled: 'Activé',
      Deleted: 'Supprimé',
      Disabled: 'Désactivé',
      Days: 'Jours',
      Hours: 'Heures',
      Minutes: 'Minutes',
      Seconds: 'Secondes',
      'Try the inject': 'Tester le stimuli',
      File: 'Fichier',
      Simulations: 'Simulations',
      Simulation: 'Simulation',
      Exercise: 'Simulation',
      Scenarios: 'Scenarios',
      Severity: 'Severité',
      Platforms: 'Plateformes',
      Detection: 'Détection',
      Detections: 'Détections',
      Asset: 'Actif',
      Assets: 'Actifs',
      'Dynamic assets': 'Actifs dynamiques',
      Active: 'Actif',
      Inactive: 'Inactif',
      Persons: 'Personnes',
      Taxonomies: 'Taxonomies',
      'Attack patterns': "Motifs d'attaque",
      AttackPatterns: "Motifs-d'attaque",
      'Kill chain phases': 'Phases de kill chain',
      KillChainPhases: 'Phases-de-kill-chain',
      'This field is mandatory': 'Ce champ est requis',
      'Remove from the context': 'Retirer de ce contexte',
      'Select a file': 'Sélectionner un fichier',
      'Do you want to delete this document?':
        'Souhaitez-vous supprimer ce document ?',
      'Update the document': 'Modifier le document',
      'Inject data': 'Données du stimuli',
      'Add teams': 'Ajouter une équipe',
      'Add target teams in this inject':
        'Ajouter des équipes cibles dans ce stimuli',
      'Targeted teams': 'Equipes ciblées',
      'Test the inject': 'Tester le stimuli',
      'All teams': 'Toutes les équipes',
      'Add target teams': 'Ajouter des équipes cibles',
      'Trigger after': 'Se déclenche après',
      'Create a new inject': 'Créer un nouveau stimuli',
      'Remove from the team': "Retirer de l'équipe",
      'Update the team': "Modifier l'équipe",
      'Update the simulation': 'Modifier la simulation',
      'Update the scenario': 'Modifier le scenario',
      'Update the inject': 'Modifier le stimuli',
      'Do you want to remove the player from the team?':
        'Souhaitez-vous retirer le joueur de cette équipe ?',
      'Add players in this team': 'Ajouter des joueurs dans cette équipe',
      'Create a new team': 'Créer une nouvelle équipe',
      'Remove from the inject': 'Retirer du stimuli',
      'Remove from the element': "Retirer de l'élément",
      'Do you want to remove the team from the inject?':
        "Souhaitez-vous retirer l'équipe du stimuli ?",
      'Do you want to delete this simulation?':
        'Souhaitez-vous supprimer cette simulation ?',
      'Number of injects': 'Nombre de stimulis',
      'No organizations in this platform':
        'Aucune organisation dans cette plateforme.',
      'No injects to send in this platform.':
        'Aucun stimuli à envoyer dans cette plateforme.',
      'Before starting the simulation, you can launch a comcheck to validate player email addresses and a dryrun to send injects to the animation team.':
        "Avant de démarrer la simulation, vous pouvez lancer une vérification pour valider les adresses emails et une simulation pour envoyer les stimulis à l'équipe d’animation.",
      'Apply a template': 'Appliquer un template',
      'Auto assign': 'Auto assignation',
      'Auto observer': 'Auto observateur',
      'Auto observer on scenarios': 'Auto obsevateur sur les scénarios',
      'Auto observer on exercises': 'Auto obsevateur sur les exercices',
      'Auto planner': 'Auto planificateur',
      'Auto planner on scenarios': 'Auto planificateur sur les scénarios',
      'Auto planner on exercises': 'Auto planificateur sur les exercices',
      'The new users will automatically be assigned to this group.':
        'Les nouveaux utilisateurs seront automatiquement assignés à ce groupe.',
      'This group will have observer permission on new simulations.':
        "Ce groupe aura la permission d'observateur sur les nouvelles simulations.",
      'This group will have planner permission on new simulations.':
        'Ce groupe aura la permission de planificateur sur les nouvelles simulations.',
      'Processed injects': 'Stimulis traités',
      'Pending injects': 'Stimulis en attente',
      'No team': 'Aucune équipe',
      'No processed injects in this simulation.':
        'Aucun stimuli traité dans cette simulation.',
      'No pending injects in this simulation.':
        'Aucun stimuli en attente dans cette simulation.',
      'Add media pressure in this inject':
        'Ajouter de la pression médiatique dans ce stimuli',
      'Kill chain phase': 'Phase de kill chain',
      Created: 'Créé',
      Updated: 'Mis à jour',
      'External ID': 'ID externe',
      'Update the attack pattern': "Modifier le motif d'attaque",
      'Create a new attack pattern': "Créer un nouveau motif d'attaque",
      'Create a new kill chain phase': 'Créer une nouvelle phase de kill chain',
      'Phase name': 'Nom de la phase',
      'Kill chain name': 'Nom de la kill chain',
      'Update the kill chain phase': 'Modifier la phase de la kill chain',
      External: 'Externe',
      openbas_email: 'Email',
      openbas_ovh_sms: 'SMS (OVH)',
      openbas_mastodon: 'Mastodon',
      openbas_lade: 'Airbus LADE',
      openbas_gnu_social: 'GNU Social',
      openbas_twitter: 'Twitter',
      openbas_http: 'Requête HTTP',
      openbas_manual: 'Manuel (rappel)',
      openbas_caldera: 'Caldera',
      openbas_atomic_red_team: 'Atomic Red Team',
      Subject: 'Sujet du mail',
      Body: 'Corps du mail',
      Encrypted: 'Chiffrer ce mail',
      Attachments: 'Pièces jointes',
      Attachment: 'Pièce jointe',
      Content: 'Contenu',
      Teams: 'Equipes',
      Version: 'Version',
      'Filigran support key': 'Clé de support Filigran',
      'Remove Filigran logos': 'Retirer les logos Filigran',
      Contextual: 'Contextuelle',
      'Send email': 'Envoyer le mail',
      'Add documents in this media pressure':
        'Ajouter des documents à cette pression médiatique',
      'Expect teams to read the article(s)':
        'Les équipes doivent lire le(s) article(s)',
      'Add media pressure': 'Ajouter de la pression médiatique',
      'Remove from the media pressure': 'Supprimer de la pression médiatique',
      'Raw request data': 'Données brutes de la requête',
      'Media pressure to publish': 'Pression médiatique à publier',
      'Form request data': 'Données de formulaire de la requête',
      Key: 'Clé',
      Headers: 'En-têtes',
      team: 'Equipe',
      attachment: 'Document',
      'Executed in': 'Exécuté en',
      'Use basic authentication': 'Utiliser une authentification basique',
      'Only in this context': 'Seulement dans ce contexte',
      Medias: 'Médias',
      Tools: 'Outils',
      Success: 'Succès',
      m: 'm',
      h: 'h',
      d: 'j',
      'Do you want to change the status of this simulation?':
        'Souhaitez-vous changer le statut de cette simulation ?',
      'will be started, do you want to continue?': 'va démarrer, voulez-vous continuer ?',
      'Injects will be paused, do you want to continue?': 'Les stimulis seront interrompues. Voulez-vous continuer ?',
      'data will be reset, do you want to restart?': 'les données seront réinitialisées, souhaitez-vous redémarrer ?',
      Confirm: 'Confirmer',
      Text: 'Texte',
      'Sender email address': "Adresse email de l'expéditeur",
      'Creation date': 'Date de création',
      'Next inject': 'Prochain stimuli',
      'Dangerous zone': 'Zone sensible',
      'Invalid user or password': "Nom d'utilisateur ou mot de passe incorrect",
      Default: 'Défaut',
      Mandatory: 'Requis',
      Optional: 'Optionnel',
      text: 'Champ texte',
      textarea: 'Zone de texte',
      tuple: 'Duo clef valeur',
      checkbox: 'Case à cocher',
      'Do you want to try this inject?': 'Souhaitez-vous tester ce stimuli ?',
      'Do you want to launch this inject?': 'Souhaitez-vous lancer ce stimuli ?',
      'The inject will only be sent to you.':
        'Le stimuli sera uniquement envoyé à vous même.',
      Try: 'Tester',
      Disable: 'Désactiver',
      Enable: 'Activer',
      'Mark as done': 'Marquer comme fait',
      'Do you want to mark this inject as done?':
        'Souhaitez-vous marquer ce stimuli comme fait ?',
      Mark: 'Marquer',
      'Do you want to disable this inject?':
        'Souhaitez-vous désactiver ce stimuli ?',
      'Do you want to enable this inject?':
        'Souhaitez-vous activer ce stimuli ?',
      'Do you want to disable this team?':
        'Souhaitez-vous désactiver cette équipe ?',
      'Do you want to enable this team?':
        'Souhaitez-vous activer cette équipe ?',
      Trigger: 'Déclencheur',
      'Manual launch': 'Lancement manuel',
      'Manage content': 'Gérer le contenu',
      Controls: 'Contrôles',
      Planning: 'Planification',
      Comchecks: 'Vérifications',
      Dryruns: 'Simulations',
      'Messages header': 'En-tête des messages',
      'Messages footer': 'Pied des messages',
      'Send a new comcheck': 'Envoyer une nouvelle vérification',
      'Launch a new dryrun': 'Démarrer une nouvelle simulation',
      Hello: 'Bonjour',
      Statistics: 'Statistiques',
      Reports: 'Rapports',
      '[${exercise.name}] Communication check':
        '[${exercise.name}] Vérification des moyens de communication',
      'This is a communication check before the beginning of the simulation. Please click on the following link in order to confirm you successfully received this message: <a href="${comcheck.url}">${comcheck.url}</a>.':
        'Ceci est une vérification des moyens de communication avant le début de la simulation. Merci de bien vouloir cliquer sur le lien ci-dessous afin de confirmer que vous avez reçu ce message avec succès : <a href="${comcheck.url}">${comcheck.url}</a>.',
      'We would like thank your for your participation in this simulation. You are kindly requested to fill this lessons learned questionnaire: <a href="${lessons_uri}">${lessons_uri}</a>.':
        "Nous souhaitons vous remercier pour votre participation à la simulation. Vous êtes cordialement invités à remplir le formulaire de retour d'expérience : <a href=\"${lessons_uri}\">${lessons_uri}</a>.",
      '[${exercise.name}] Lessons learned questionnaire':
        "[${exercise.name}] Questionnaire de retour d'expérience",
      'Best regards': 'Bien cordialement',
      'The simulation control team': "L'équipe d'animation de la simulation",
      'Do you want to launch a new dryrun?':
        'Souhaitez-vous lancer une nouvelle simulation ?',
      'Add tags to this simulation': 'Ajouter des tags à cette simulation',
      'Add tags to this scenario': 'Ajouter des tags à ce scenario',
      'No comcheck in this simulation.': 'Aucune vérification dans cette simulation',
      'There is nothing to see here...': "Il n'y a rien à voir ici...",
      'Send the lessons learned questionnaire':
        "Envoyer le questionnaire de retour d'expérience",
      Comments: 'Commentaires',
      'Comment (optional)': 'Commentaire (optionnel)',
      "What didn't work well": "Ce qui n'a pas bien fonctionné",
      'What worked well': 'Ce qui a bien fonctionné',
      'Global evaluation': 'Evaluation globale',
      'Your overall evaluation about this question.':
        'Votre évaluation générale à propos de cette question.',
      'Do you want to submit your answers? You will not be able to change them later.':
        'Souhaitez-vous soumettre vos réponses ? Vous ne pourrez pas les changer plus tard.',
      Check: 'Vérification',
      Preview: 'Aperçu',
      None: 'Aucune',
      message: 'Message',
      Pending: 'En attente',
      State: 'Etat',
      'Sent date': "Date d'envoi",
      'Received date': 'Date de réception',
      'Communication check': 'Vérification des moyens de communication',
      Running: 'En cours',
      Failure: 'Echec',
      Expired: 'Expiré',
      Anonymized: 'Anonymisé',
      'No media pressure entry in this channel yet.':
        'Encore aucune entrée de pression médiatique dans ce média.',
      'Your communication check is': 'Votre test de communication est',
      successful: 'un succès',
      answers: 'réponses',
      'of which': 'dont',
      'contain comments': 'contiennent des commentaires',
      'Verification done at': 'Vérification faite le',
      'No dryrun in this simulation.': 'Aucune simulation dans cette simulation.',
      'No objectives in this simulation.': 'Aucun objectif dans cette simulation.',
      'There is no evaluation for this objective yet': 'Il n’y a pas encore d’évaluation pour cet objectif',
      'Do you want to delete this dryrun?':
        'Souhaitez-vous supprimer cette simulation ?',
      'Overall objectives score': 'Score global des objectifs',
      'Do you want to delete this poll?':
        'Souhaitez-vous supprimer ce sondage ?',
      'Update the poll': 'Modifier le sondage',
      'Simulation logs': 'Journal de la simulation',
      'Poll replies': 'Réponses au sondage',
      Overview: 'Aperçu',
      Objectives: 'Objectifs',
      'Create a new objective': 'Créer un nouvel objectif',
      'Update the objective': "Modifier l'objectif",
      'Do you want to delete this objective?':
        'Souhaitez-vous supprimer cet objectif ?',
      'Write an entry': 'Ecrire une entrée',
      'Do you want to delete this log?':
        'Souhaitez-vous supprimer cette entrée ?',
      'Objective achievement evalution':
        "Evaluation de l'atteinte de l'objectif",
      Evaluate: 'Evaluer',
      'My evaluation': 'Mon évaluation',
      Priority: 'Priorité',
      Polls: 'Sondages',
      'Create a new poll': 'Créer un nouveau sondage',
      'Update the log': "Modifier l'entrée",
      'Create a new user': 'Créer un nouvel utilisateur',
      'Dryrun recipients': 'Destinataires de la simulation',
      'Create a new report': 'Créer un nouveau rapport',
      'Do you want to delete this report?':
        'Souhaitez-vous supprimer ce rapport ?',
      'Update the report': 'Modifier le rapport',
      token: 'Token du compte',
      status: 'Statut',
      'Inject documents': 'Documents du stimuli',
      'Add documents': 'Ajouter des documents',
      'Add documents in this inject': 'Ajouter des documents dans ce stimuli',
      Yes: 'Oui',
      No: 'Non',
      'Not applicable': 'Non applicable',
      'Enable attachment': 'Activer la pièce jointe',
      'Disable attachment': 'Désativer la pièce jointe',
      'Do you want to remove the document from the element?':
        'Souhaitez-vous retirer ce document de cet élément ?',
      'Import a simulation': 'Importer une simulation',
      Export: 'Exporter',
      'Export the simulation': 'Exporter cette simulation',
      'Export the scenario': 'Exporter ce scenario',
      'Do you want to delete the scenario?': 'Voulez-vous supprimer ce scénario?',
      'Reset to default values': 'Réinitialiser les valeurs par défaut',
      Elements: 'Eléments',
      'Scenario (including attached files)':
        'Scénario (fichiers joints inclus)',
      'Send an email': 'Envoyer un email',
      'Send a SMS': 'Envoyer un SMS',
      'To fill': 'A remplir',
      Username: "Nom d'utilisateur",
      Unknown: 'Inconnu',
      'No value': 'Aucune valeur',
      'Primary color (dark)': 'Couleur primaire (sombre)',
      'Secondary color (dark)': 'Couleur secondaire (sombre)',
      'Primary color (light)': 'Couleur primaire (clair)',
      'Secondary color (light)': 'Couleur secondaire (clair)',
      logo: 'Logo seulement',
      'Title only': 'Titre seulement',
      'logo-title': 'Logo et titre',
      'Dark theme': 'Thème sombre',
      'Light theme': 'Thème clair',
      'Header mode': 'Mode du bandeau supérieur',
      'Select an image': 'Sélectionner une image',
      'Create an image': 'Créer une image',
      'Change logo': 'Changer le logo',
      'Scheduled / in use': 'Planifié / utilisé',
      'Not used in the context': 'Pas utilisé dans ce contexte',
      'Update the media pressure': 'Modifier la pression médiatique',
      'Do you want to delete this media pressure?':
        'Souhaitez-vous supprimer cette pression médiatique ?',
      'Do you want to delete this challenge?':
        'Souhaitez-vous supprimer ce challenge ?',
      'Create a new media pressure': 'Créer une nouvelle pression médiatique',
      'Collaborative lessons learned': "Retour d'expérience collaboratif",
      Answers: 'Réponses',
      'Categories and questions': 'Catégories et questions',
      Questions: 'Questions',
      Empty: 'Vider',
      'Objective achievement evaluation':
        "Evaluation de l'atteinte de l'objectif",
      'Crisis intensity (injects by hour)':
        'Intensité de la crise (stimulis par heure)',
      'Apply a lessons learned template':
        "Appliquer un template de retour d'expérience",
      'Questionnaire mode': 'Mode du questionnaire',
      'Anonymize answers': 'Anonymiser les réponses',
      'No explanation': 'Aucune explication',
      'Add target teams in this lessons learned category':
        "Ajouter des équipes cibles à cette catégorie de retour d'expérience",
      'Sending the questionnaire will emit an email to each player with a unique link to access and fill it.':
        'Envoyer le questionnaire va émettre un email à chaque joueur avec un lien unique pour y accéder et le remplir.',
      'Do you want to empty lessons learned categories and questions?':
        "Souhaitez-vous vider les catégories et les questions de retour d'expérience ?",
      'Do you want to reset lessons learned answers?':
        "Souhaitez-vous réinitialiser les réponses du retour d'expérience ?",
      Reset: 'Réinitialiser',
      Campaign: 'Campagne',
      Duration: 'Durée',
      'Send the questionnaire': 'Envoyer le questionnaire',
      'Reset answers': 'Réinitialiser les réponses',
      hours: 'heures',
      Apply: 'Appliquer',
      players: 'joueurs',
      Explanation: 'Explication',
      Category: 'Catégorie',
      'Create a new challenge': 'Créer un nouveau challenge',
      Channel: 'Média',
      Author: 'Auteur',
      'Max number of attempts': "Nombre maximum d'essais",
      'Add documents in this challenge': 'Ajouter un document à ce challenge',
      'At least one flag is required for a challenge.':
        'Au moins un flag est requis pour un challenge.',
      'Text (case-sensitive)': 'Texte (sensible à la casse)',
      'Regular expression': 'Expression régulière',
      'Update the challenge': 'Modifier le challenge',
      'Challenges to publish': 'Challenges à publier',
      'Add challenge in this inject': 'Ajouter des challenges à ce stimuli',
      'Add challenges': 'Ajouter des challenges',
      'Do you want to remove this media pressure from the inject?':
        'Souhaitez-vous retirer cette pression médiatique de ce stimuli ?',
      'Do you want to remove this challenge from the inject?':
        'Souhaitez-vous retirer ce challenge de ce stimuli ?',
      VALUE: 'Texte',
      VALUE_CASE: 'Texte (sensible à la casse)',
      REGEXP: 'Expression régulière',
      'No category': 'Aucune catégorie',
      'No challenge in this simulation yet.':
        'Encore aucun challenge dans cette simulation.',
      'Distribution of expectations by team':
        'Distribution des attendus par équipe',
      'Distribution of expectations by inject type':
        'Distribution des attendus par type de stimuli',
      'Distribution of expected total score by inject type':
        'Distribution du score total attendu par type de stimuli',
      '-': 'Aucun',
      'Each team should upload a document':
        'Chaque équipe doit uploader un document',
      'Each team should submit a text response':
        'Chaque équipe doit soumettre une réponse texte',
      // -- Expectation start --
      'This expectation is handled automatically by the platform and triggered when team reads articles': 'Cet attendu est géré automatiquement par la plateforme et déclenché lorsque une équipe lit les articles',
      'Add expectations': 'Ajouter des attendus',
      'Add expectation in this inject': 'Ajouter des attendus dans ce stimuli',
      'Update the expectation': 'Modifier l\'attendu',
      'Do you want to delete this expectation ?': 'Voulez vous supprimer cet attendu ?',
      'Number of expectations': "Nombre d'attendus",
      'Inject expectations': 'Attendus du stimuli',
      'Manual expectations': 'Attendus manuels',
      'Expectations of ': 'Attendus de',
      MANUAL: 'Manuel',
      ARTICLE: 'Automatique - Déclenché lorsque l\'équipe a lu l\'article',
      DETECTION: 'Automatique - Detection: Déclenché lorsque l\'injection est traitée',
      PREVENTION: 'Automatique - Prevention: Déclenché lorsque l\'injection est traitée',
      TYPE_ARTICLE: 'Article',
      TYPE_CHALLENGE: 'Défi',
      TYPE_DETECTION: 'Detection',
      TYPE_MANUAL: 'Manuel',
      TYPE_PREVENTION: 'Prevention',
      TYPE_HUMAN_RESPONSE: 'Réponse humaine',
      FAILED: 'Echoué',
      VALIDATED: 'Validé',
      Done: 'Fait',
      Draft: 'Brouillon ',
      Failed: 'Echoué',
      'Pending result': 'Résultat en attente',
      'Validation mode': 'Type de validation',
      'All assets (per group) must validate the expectation': 'Tous les actifs (par groupe) doivent valider l\'attente',
      'At least one asset (per group) must validate the expectation': 'Au moins un actif (par groupe) doit valider l\'attente',
      'An isolated asset is considered as a group of one asset': 'Un actif isolé est considéré comme un groupe d\'un seul actif',
      // -- Expectation end --
      'Distribution of expected total score by team':
        'Distribution du score total attendu par équipe',
      'Simulation definition and scenario':
        'Définition de la simulation et scénario',
      'Simulation results': 'Résultats de la simulation',
      'Simulation data': 'Données de la simulation',
      'Distribution of total score by team':
        'Distribution du score total par équipe',
      'Distribution of total score by organization':
        'Distribution du score total par organisation',
      'Total expected score': 'Score total attendu',
      'Distribution of total score by player':
        'Distribution du score total par joueur',
      'Distribution of total score by inject':
        'Distribution du score total par stimuli',
      'Distribution of injects by type': 'Distribution des stimulis par type',
      'Distribution of injects by team':
        'Distribution des stimulis par équipe',
      'Distribution of mails by team':
        'Distribution des mails par équipe',
      'Distribution of mails by player': 'Distribution des mails par joueur',
      'Distribution of mails by inject': 'Distribution des mails par stimuli',
      'Sent injects over time': 'Stimulis envoyés dans le temps',
      'Sent mails over time': 'Emails envoyés dans le temps',
      'No data to display or the simulation has not started yet':
        "Aucune donnée disponible ou la simulation n'a pas encore commencé",
      'Back to administration': "Retour à l'administration",
      'Teams scores over time': 'Score des équipes dans le temps',
      'Inject types scores over time':
        'Score des types de stimuli dans le temps',
      'The animation team can validate the team reaction':
        "L'équipe d'animation peut valider la réaction de l'équipe",
      Description: 'Description',
      'No description': 'Aucune description',
      'Only injects with manual validation':
        'Seulement les stimulis avec validation manuelle',
      'Pending reading': 'Lecture en attente',
      'Pending submission': 'Soumission en attente',
      'Pending validation': 'Validation en attente',
      Validations: 'Validations',
      Type: 'Type',
      Validate: 'Valider',
      Validated: 'Validé',
      Error: 'Erreur',
      'This page is not found on this OpenBAS application.': 'Cette page est introuvable sur l\'application OpenBAS.',
      'You must be logged to access this page': 'Vous devez être connecté pour accéder à cette page',
      // Challenges
      Challenges: 'Challenges',
      // Variables
      'Available variables': 'Variables disponibles',
      Variables: 'Variables',
      'Create a new variable': 'Créer une nouvelle variable',
      'Do you want to delete the variable ?': 'Voulez vous supprimer cette variable ?',
      'Update the variable': 'Mettre à jour la variable',
      'Invalid input. Please use only letters or underscores, and ensure the field is not empty.':
        "Saisie invalide. Merci d'utiliser uniquement des lettres ou des tirets bas, et de vous assurer que le champ n'est pas vide.",
      'Builtin variables': 'Variables intégrées',
      'Custom variables': 'Variables personnalisées',
      'Please follow this link to': 'Merci de suivre ce lien pour',
      'manage custom variables': 'gérer les variables personnalisées',
      'view custom variables': 'afficher les variables personnalisées',
      'Variable values': 'Valeurs des Variables',
      // MDEditor
      'Edit code': 'Edition',
      'Live code': 'Code en temps réel',
      'Preview code': 'Prévisualisation',
      Shares: 'Nombre de partages',
      Likes: 'Nombre de likes',
      'Read more': 'Lire plus',
      'JAVA Virtual Machine': 'Machine virtuelle JAVA',
      'Latest stable build': 'Dernière version stable',
      'API specifications': 'Spécifications de l\'API',
      Theme: 'Thème',
      'OpenBAS platform': 'Plateforme OpenBAS',
      'Enable Enterprise Edition': 'Activer l\'édition enterprise',
      PostgreSQL: 'PostgreSQL',
      'Token key': 'Token',
      Example: 'Exemple',
      Score: 'Score',
      Message: 'Message',
      'New control': 'Nouveau contrôle',
      'Percent of reached score': 'Pourcentage du score atteint',
      Pause: 'Pause',
      Resume: 'Reprendre',
      injects: 'injects',
      Paused: 'En pause',
      Canceled: 'Annulé',
      Partial: 'Partiel',
      'Quick inject definition': 'Définition rapide de l’injection',
      Order: 'Ordre',
      Details: 'Détails',
      Team: 'Equipe',
      Template: 'Modèle',
      Questionnaire: 'Questionnaire',
      User: 'Utilisateur',
      'General information': 'Informations générales',
      'Simulation definition statistics': 'Statistiques de la définition de la simulation',
      'Simulation definition scores': 'Scores de la définition de la simulation',
      'Simulation data statistics': 'Statistiques des données de la simulation',
      'Simulation results statistics': 'Statistiques des résultats de la simulation',
      'Lessons learned objectives': 'Objectifs des leçons apprises',
      'Lessons learned statistics': 'Statistiques des leçons apprises',
      'Lessons learned details': 'Détails des leçons apprises',
      Logos: 'Logos',
      toggle: 'Basculer',
      Collapse: 'Réduire',
      Animation: 'Animation',
      'API access': 'Accès à l’API',
      RENEW: 'RENOUVELER',
      Granted: 'Accordé',
      submitted: 'Soumis',
      failed: 'Échoué',
      Question: 'Question',
      By: 'Par',
      'Should not be empty': 'Ne doit pas être vide',
      // Assets
      Endpoints: 'Endpoints',
      'Teams of players': 'Equipes de joueurs',
      'Create a new endpoint': 'Créer un nouvel endpoint',
      'Update the endpoint': 'Modifier l\'endpoint',
      'Do you want to delete the endpoint ?': 'Souhaitez-vous supprimer cet endpoint ?',
      Hostname: 'Nom d\'hôte',
      'Ip Addresses': 'Addresse Ips',
      'Ip Address': 'Addresse Ip',
      'Ip Address {index}': 'Addresse Ip {index}',
      'Please provide one IP address per line.': 'Veuillez fournir une adresse IP par ligne.',
      'Invalid Ip Address': 'Addresse Ip non valide',
      'Last Seen': 'Vu pour la dernière fois',
      'MAC Addresses': 'Adresses MAC',
      'Please provide one MAC address per line.': 'Veuillez fournir une adresse MAC par ligne.',
      'Invalid MAC address': 'Mac adresse non valide',
      Platform: 'Plateforme',
      'Collected by': 'Collecté par',
      'Targeted asets': 'Actifs ciblés',
      'Add assets': 'Ajouter des actifs',
      'Add assets in this inject': 'Ajouter des actifs dans ce stimuli',
      'Show all assets': 'Afficher tous les actifs',
      'By default, only assets compliant with the injector are displayed': 'Par défaut, seuls les actifs conformes à l\'injecteur sont affichés',
      // Asset groups
      'Asset groups': 'Groupe d\'assets',
      AssetGroup: 'Groupe-d-assets',
      AssetGroups: 'Groupes-d-assets',
      'Dynamic asset filter': 'Filtre d\'actifs dynamique',
      'Filter allowing assets to be added dynamically to this group': 'Filtre permettant d\'ajouter dynamiquement des actifs à ce groupe',
      'Create a new asset group': 'Créer un nouvel asset group',
      'Update the asset group': 'Modifier l\'asset group',
      'Manage assets': 'Gérer les actifs',
      'Add assets in this asset group': 'Ajouter des actifs dans ce groupe d\'actifs',
      'Remove from the asset group': 'Retirer de ce groupe d\'asset',
      'Targeted assets': 'Assets ciblés',
      'Targeted asset groups': 'Groupes d\'assets ciblés',
      'Add asset groups': 'Ajouter des groupes d\'assets',
      'Add asset groups in this inject': 'Ajouter des groupes d\'assets dans ce stimuli',
      'Media pressure': 'Pression médiatique',
      Home: 'Accueil',
      'Atomic testings': 'Tests atomiques',
      Components: 'Composants',
      Skills: 'Compétences',
      Mitigations: 'Endiguements',
      'Search the platform': 'Rechercher dans la plateforme',
      'Advanced search': 'Recherche avancée',
      Notifications: 'Notifications',
      'Filigran eXtended Threat Management': 'Filigran eXtended Threat Management',
      'Platform connected': 'Plateforme connectée',
      'Get OpenCTI now': 'Obtenir OpenCTI maintenant',
      'Current platform': 'Plateforme courante',
      Personas: 'Personas',
      'The country code and mobile phone number provided is invalid. Please provide a valid number': 'L\'indicatif du pays et le numéro de téléphone mobile fournis ne sont pas valides. Veuillez fournir un numéro valide',
      phone_number_tooltip: 'Le numéro de téléphone devrait commencer par un signe plus ( + )\n'
        + 'Il peut contenir des espaces ou des tirets ( – ) ou des parenthèses.\n',
      'Instantiate a simulation': 'Créer une nouvelle simulation',
      // -- FILTERS --
      'Add filter': 'Ajout d\'un filtre',
      'Clear filters': 'Supprimer les filtres',
      AND: 'ET',
      OR: 'OU',
      // Endpoint
      endpoint_hostname: 'Nom d\'hôte',
      endpoint_ips: 'Addresse Ips',
      endpoint_platform: 'Platforme',
      endpoint_arch: 'Architecture',
      endpoint_agent_version: 'Version de l\'agent',
      Recurrence: 'Récurrence',
      'Does not repeat': 'Ne se répète pas',
      Daily: 'Quotidien',
      Weekly: 'Hebdomadaire',
      Monthly: 'Mensuel',
      'Set daily recurrence': 'Définir la récurrence quotidienne',
      'Set weekly recurrence': 'Définir la récurrence hebdomadaire',
      'Set monthly recurrence': 'Définir la récurrence mensuelle',
      'Week of month': 'Semaine du mois',
      First: 'Première',
      Second: 'Deuxième',
      Third: 'Troisième',
      Fourth: 'Quatrième',
      'Day of week': 'Jour de la semaine',
      Monday: 'Lundi',
      Tuesday: 'Mardi',
      Wednesday: 'Mercredi',
      Thursday: 'Jeudi',
      Friday: 'Vendredi',
      Saturday: 'Samedi',
      Sunday: 'Dimanche',
      Scheduling_time: 'Heure',
      Save: 'Enregistrer',
      'Launch a simulation or start a recurring simuation from this scenario': 'Lancer une simulation ou démarrer une simulation récurrente à partir de ce scénario',
      recurrence_The: 'Le',
      recurrence_at: 'à',
      recurrence_from: 'du',
      recurrence_to: 'au',
      recurrence_starting_from: 'à partir du',
      recurrence_Last: 'Dernière',
      'No scheduling': 'Pas de planification',
      Scheduling: 'Planification',
      'End date need to be stricly after start date': '',
      'The time and start date do not match, as the time provided is either too close to the current moment or in the past': 'Il y a un décalage entre l\'heure et la date de début (l\'heure est soit trop proche de maintenant, soit dans le passé)',
      'Only weekday': 'Seulement la semaine',
      // Atomic Testing
      'Attack started': "Début de l'attaque",
      'Attack ended': "Fin de l'attaque",
      'Attack Detected': 'Attaque détectée',
      'Validation Success': 'Attaque réussie',
      'Attack Blocked': 'Attaque bloquée',
      'Attack Not Detected': 'Attaque non détectée',
      'Validation Failed': "Échec de l'attaque",
      'Attack Unblocked': 'Attaque débloquée',
      'Waiting Response': 'En attente',
      'Inject Execution Status': "Statut d'exécution injecté",
      'Global score': 'Score global',
      'Execution date': 'Date d\'exécution',
      'Execution details': 'Détails d\'exécution',
      'Last Start Execution Date': "Dernière date de début d'exécution",
      'No targets available': 'Aucune cible disponible',
      'No target data available': 'Aucune donnée de cible disponible',
      'Targets response': 'Réponse des cibles',
      'Update the atomic testing': 'Mettre à jour le test atomique',
      'Create a new atomic test': 'Créer un nouveau test atomique',
      'Mitre Filter': 'Filtre Mitre',
      techniques: 'Techniques',
      'Unknown Data': 'Données inconnues',
      'No data available': 'Aucune donnée disponible (répété)',
      Expectations: 'Objectifs',
      'Execution logs': "Logs d'exécution",
      Target: 'Cible',
      Traces: 'Traces',
      'Tracking Sent Date': 'Date d\'envoi',
      'Tracking Ack Date': 'Date de réception',
      'Tracking End Date': 'Date de fin',
      'Tracking Total Execution': 'Durée totale d\'exécution',
      Time: 'Temps',
      'Tracking Total Count': 'Nombre total d\'exécutions',
      'Tracking Total Error': 'Nombre total d\'échecs',
      'Tracking Total Success': 'Nombre total de succès',
      'global-crisis': 'Crise mondiale',
      'attack-scenario': "Scénario d'attaque",
      'media-pressure': 'Pression médiatique',
      'data-exfiltration': 'Exfiltration de données',
      'capture-the-flag': 'Capture de drapeau',
      'vulnerability-exploitation': 'Exploitation des vulnérabilités',
      'lateral-movement': 'Mouvement latéral',
      'url-filtering': 'Filtrage URL',
      'endpoint-protection': 'Protection des points de terminaison',
      'web-filtering': 'Filtrage web',
      'incident-response': 'Réponse aux incidents',
      'standard-operating-procedure': "Procédures d'exploitation standard",
      'crisis-communication': 'Communication de crise',
      'strategic-reaction': 'Réaction stratégique',
      'managed assets': 'actifs gérés',
      'Search by target name': 'Recherche par nom de cible',
      contains: 'contient',
      'not contains': 'ne contient pas',
      equals: 'egal',
      'not equals': 'pas égal',
      'starts with': 'commence par',
      'not starts with': 'ne commence pas par',
      and: 'et',
      Agents: 'Agents',
      'Learn more information about how to setup simulation agents': 'En savoir plus sur la configuration des agents de simulation',
      'in the documentation': 'dans la documentation',
      'Installation path': "Chemin d'installation",
      Architecture: 'Architecture',
      AMD64: 'AMD64',
      ARM64: 'ARM64',
      Download: 'Télécharger',
      documentation: 'documentation',
      'IP Addresses': 'Adresses IP',
      'Kill Chain Phases': 'Phases de la Kill Chain',
      'Attack Patterns': "Modèles d'attaque",
      Targets: 'Cibles',
      'Results by target': 'Résultats par cible',
      Configuration: 'Configuration',
      'No logs available': 'Aucun journal disponible',
      'Add documents in this media pressure article': 'Ajouter des documents dans cet article de pression médiatique',
      'Update the media pressure article': "Mettre à jour l'article de pression médiatique",
      'Create an article': 'Créer un article',
      'Create a new media pressure article': 'Créer un nouvel article de pression médiatique',
      'Create an inject': 'Créer un stimuli',
      'Enable AI powered platform': "Activer la plateforme alimentée par l'IA",
      'Filigran Enterprise agreement': "Accord d'entreprise Filigran",
      'I have read and agree to the': "J'ai lu et j'accepte les",
      'OpenBASEE license terms': 'termes de la licence OpenBASEE',
      'Kill Chain Phase': 'Kill chain d\'intrusion',
      'Ask AI': "Demander à l'IA",
      'Generate a message': 'Générer un message',
      'Generate an article': 'Générer un article',
      'Make it shorter': 'Raccourcir',
      'Make it longer': 'Allonger',
      'Change tone': 'Changer le ton',
      Summarize: 'Résumer',
      Explain: 'Expliquer',
      Retry: 'Réessayer',
      'Select options': 'Sélectionner des options',
      Tone: 'Ton',
      Formal: 'Formel',
      Informal: 'Informel',
      Authoritative: 'Autoritaire',
      Assertive: 'Assuré',
      Bitter: 'Amer',
      Arrogant: 'Arrogant',
      Aggressive: 'Agressif',
      Sarcastic: 'Sarcastique',
      'Number of paragraphs': 'Nombre de paragraphes',
      Context: 'Contexte',
      Generate: 'Générer',
      Tactical: 'Tactique',
      Operational: 'Opérationnel',
      Strategic: 'Stratégique',
      'Select an inject in the left panel': 'Sélectionner un stimuli dans le panneau de gauche',
      'Inject content': 'Injecter le contenu',
      'List view': 'Vue en liste',
      'Distribution view': 'Vue de distribution',
      'No expectation for': 'Aucune attente pour',
      'validations needed': 'validations nécessaires',
      'Add tags': 'Ajouter des étiquettes',
      '24 hours': '24 heures',
      'Asset Groups': "Groupes d'actifs",
      Values: 'Valeurs',
      'No available options': 'Aucune option disponible',
      selected: 'sélectionné',
      'Update objects': 'Mettre à jour les objets',
      'Action type': "Type d'action",
      Replace: 'Remplacer',
      Field: 'Champ',
      'Create a new payload': 'Créer une nouvelle charge utile',
      'Windows Command Line': 'Ligne de commande Windows',
      'Windows Powershell': 'Windows Powershell',
      'Update the payload': 'Mettre à jour la charge utile',
      Payloads: 'Charges utiles',
      'Number of simulations': 'Nombre de simulations',
      'Performance Overview': "Vue d'ensemble des performances",
      'Top simulation categories': 'Principales catégories de simulation',
      'Top attack patterns': "Principaux modèles d'attaque",
      'Last simulations': 'Dernières simulations',
      Collectors: 'Collecteurs',
      'Updated at': 'Mis à jour à',
      Executors: 'Exécuteurs',
      Injectors: 'Injecteurs',
      InjectorContracts: "Contrats d'injecteur",
      'Create a new injector contract': "Créer un nouveau contrat d'injecteur",
      'SelectField the template': 'Sélectionner le modèle de champ',
      'Create the injector contract': "Créer le contrat d'injecteur",
      'Read only': 'Lecture seule',
      'Default value': 'Valeur par défaut',
      'Update the injector contract': "Mettre à jour le contrat d'injection",
      'Supporting adding new contracts': "Supporte l'ajout de nouveaux contrats",
      'Create a new mitigation': 'Créer une nouvelle atténuation',
      'Update the mitigation': "Mettre à jour l'atténuation",
      People: 'Personnes',
      'Install simulation agents': 'Installer des agents de simulation',
      'Modify the scheduling': 'Modifier la planification',
      'Not scheduled': 'Non programmé',
      'Threat intelligence': 'Renseignement sur les menaces',
      'Main Focus': 'Focus principal',
      'No inject in this scenario': 'Aucun stimuli dans ce scénario',
      'Simulations Results': 'Résultats des simulations',
      'Simulate Now': 'Simuler maintenant',
      'Human Response': 'Réponse humaine',
      'Mail configuration': 'Configuration du courrier',
      'Not planned': 'Non prévu',
      'Endpoint Protection': 'Protection des points de terminaison',
      'Web Filtering': 'Filtrage web',
      'Incident Response': 'Réponse aux incidents',
      'Standard Operating Procedures': "Procédures d'exploitation standard",
      'Crisis Communication': 'Communication de crise',
      'Strategic Reaction': 'Réaction stratégique',
      Low: 'Faible',
      Medium: 'Moyen',
      High: 'Élevé',
      Critical: 'Critique',
      scenarios: 'scénarios',
      'Phase short name': 'Nom court de la phase',
      'External Id': 'Id externe',
      'Disable Enterprise Edition': "Désactiver l'édition Enterprise",
      Enterprise: 'Entreprise',
      Community: 'Communauté',
      'AI Powered': "Alimenté par l'IA",
      'Missing token': 'Jeton manquant',
      RabbitMQ: 'RabbitMQ',
      backlabel: 'étiquette de retour',
      backuri: 'uri de retour',
      'Injects Results': 'Résultats des stimulis',
      'Import injects': 'Importer des stimulis',
      'Browse the link': 'Parcourir le lien',
      EE: 'EE',
      'Error or prevented': 'Erreur ou empêché',
      'Attack Executed': 'Attaque exécutée',
      Accept: 'Accepter',
      YYYY: 'AAAA',
      'Copied to clipboard': 'Copié dans le presse-papiers',
      'OpenBAS EE license terms': 'Conditions de licence OpenBAS EE',
      'Main focus': 'Focus principal',
      'All categories': 'Toutes les catégories',
      'Install Windows Agent': "Installer l'agent Windows",
      'Install Linux Agent': "Installer l'agent Linux",
      'Install MacOS Agent': "Installer l'agent MacOS",
      'Install Browser Agent': "Installer l'agent navigateur",
      'Install a simulation agent': 'Installer un agent de simulation',
      'To install the agent please follow the': "Pour installer l'agent, veuillez suivre le",
      Linux: 'Linux',
      Windows: 'Windows',
      MacOS: 'MacOS',
      OpenCTI: 'OpenCTI',
      OpenBAS: 'OpenBAS',
      OpenERM: 'OpenERM',
      OpenMTD: 'OpenMTD',
      Authorization: 'Autorisation',
      English: 'Anglais',
      French: 'Français',
      Chat: 'Discussion',
      Source: 'Source',
      Result: 'Résultat',
      'Last execution date': 'Dernière date d\'exécution',
      Configure: 'Configurer',
      'Missing content': 'Contenu manquant',
      'INJECT EXECUTED': 'STIMULI EXECUTE',
      'Select the template': 'Sélectionnez le modèle',
      'Supporting payloads': 'Charges utiles prises en charge',
      'Command Line': 'Ligne de commande',
      Executable: 'Exécutable',
      'File Drop': 'Dépôt de fichier',
      'DNS Resolution': 'Résolution DNS',
      'Network Traffic': 'Trafic réseau',
      'Select the type': 'Sélectionnez le type',
      'Create the payload': 'Créer la charge utile',
      'Command executor': 'Exécuteur de commandes',
      PowerShell: 'PowerShell',
      'Command Prompt': 'Invite de commandes',
      Bash: 'Bash',
      Sh: 'Sh',
      Command: 'Commande',
      'Executable file': 'Fichier exécutable',
      'File to drop': 'Fichier à déposer',
      'One hostname by line': "Un nom d'hôte par ligne",
      Arguments: 'Arguments',
      'Default Value': 'Valeur par défaut',
      Prerequisites: 'Prérequis',
      'Get command': 'Obtenir la commande',
      'Check command': 'Vérifier la commande',
      'Cleanup executor': 'Exécuteur de nettoyage',
      'Cleanup command': 'Commande de nettoyage',
      Document: 'Document',
      // Policies
      'Platform login message': 'Messages de connexion',
      'Platform consent message': 'Message de consentement à la plate-forme',
      'Platform consent confirm text': 'Texte de confirmation du consentement à la plate-forme',
      Write: 'Ecriture',
      // Timeline
      'Hide timeline': 'Cacher la chronologie',
      'Show Timeline': 'Afficher la chronologie',
      COMMUNITY: 'Community',
      FILIGRAN: 'Filigran',
      VERIFIED: 'Verified',
      UNVERIFIED: 'Unverified',
      // ---Xls mapper
      'Create a xls mapper': 'Créer un mapper xls',
      'Mapper name': 'Nom du mapper',
      'Inject type column': 'Colonne de type d\'inject',
      'Representation for inject type': 'Représentation de l\'inject type',
      'Inject importer name': 'Nom d\'inject importer',
      'Matching type in the xls': 'Type correspondant dans le xls',
      'Inject importer description': 'Description d\'inject importer',
      'Inject type': 'Typed d\'inject',
      'Inject importer rules': 'Règles d\'inject importer',
      'At least one inject type is required': 'Au moins un inject type est requis',
      'New representation': 'Nouvelle représentation',
      'Rule attribute name': 'Nom de règle d\'attribut',
      'Rule attribute columns': 'Colonnes de règle d\'attribut',
      'Time pattern': 'Modèle de temps',
      'Rule title': 'Titre de la règle',
      'Rule description': 'Description de la règle',
      'Do you want to delete this representation?': 'Voulez-vous supprimer cette représentation ?',
      'Trigger time': 'Heure de lancement',
      'Attribute mapping configuration': 'Configuration d\'attribut de mappeur',
      Test: 'Test',
      'Do you want to delete this XLS mapper ?': 'Voulez-vous supprimer ce mappage XLS ?',
      Expectation_name: 'Nom de l\'attendu',
      Expectation_description: 'Description de l\'attendu',
      Expectation_score: 'Score de l\'attendu',
      ABSOLUTE_TIME_WITHOUT_START_DATE: 'L\'import contient des injects qui se déclenche à une certaine heure de la journée (ex: 9h30) mais le scenario n\'a pas de date de départ. Veuillez spécifier une date de départ.',
      Trigger_time: 'Temps de déclenchement',
      'This expression will be used to find a match in the specified column to determine the inject type. Regular Expressions can be used.': 'Cette expression est utilisé pour déterminer si il y a correspondance avec la colonne spécifié. L\'utilisation d\'expression régulière est possible.',
      'By default we accept iso date (YYYY-MM-DDThh:mm:ss[.mmm]TZD), but you can specify your own date format in ISO notation (for instance DD.MM.YYYY hh\'h\'mm)': 'Par défaut nous acceptons la date iso (AAAA-MM-JJ hh:mm:ss[.mmm]TZD), mais vous pouvez spécifiez votre propre format de date en notation ISO (par exemple JJ.MM.AAAA hh\'h\'mm)',
      // -- Lessons --
      'Lessons learned': 'Expérience',
      'Create a new lessons learned template':
        "Créer un nouveau template de retour d'expérience",
      'Update the lessons learned template':
        "Modifier le template de retour d'expérience",
      'Do you want to delete this lessons learned template?':
        "Souhaitez-vous supprimer ce template de retour d'expérience ?",
      'Create a new lessons learned category':
        "Créer une catégorie de retour d'expérience",
      'Update the lessons learned category':
        "Modifier une catégorie de retour d'expérience",
      'Do you want to delete this lessons learned category?':
        "Souhaitez-vous supprimer cette catégorie de retour d'expérience ?",
      'Create a new lessons learned question':
        "Créer une nouvelle question de retour d'expérience",
      'Update the lessons learned question':
        "Modifier la question de retour d'expérience",
      'Do you want to delete this lessons learned question?':
        "Souhaitez-vous supprimer cette question de retour d'expérience ?",
    },
    en: {
      openbas_email: 'Email',
      openbas_ovh_sms: 'SMS (OVH)',
      openbas_mastodon: 'Mastodon',
      openbas_manual: 'Manual (reminder)',
      openbas_caldera: 'Caldera',
      openbas_lade: 'Airbus LADE',
      openbas_gnu_social: 'GNU Social',
      openbas_twitter: 'Twitter',
      openbas_http: 'HTTP Request',
      openbas_atomic_red_team: 'Atomic Red Team',
      Subject: 'Email subject',
      Body: 'Email body',
      Encrypted: 'Encrypt this email',
      Attachments: 'Attachments',
      team: 'Team',
      text: 'Text fields',
      textarea: 'Text area',
      tuple: 'Key value pair',
      checkbox: 'Checkbox',
      attachment: 'Document',
      message: 'Message',
      token: 'Account token',
      status: 'Status',
      Running: 'On-going',
      newspaper: 'Newspaper',
      tv: 'TV channel',
      microblogging: 'Microblogging',
      logo: 'Logo only',
      'logo-title': 'Logo and title',
      VALUE: 'Text',
      VALUE_CASE: 'Text (case-sensitive)',
      REGEXP: 'Regular expression',
      '-': 'None',
      MANUAL: 'Manual',
      ARTICLE: 'Automatic - Triggered when team reads articles',
      DETECTION: 'Automatic - Detection: Triggered when inject is processed',
      PREVENTION: 'Automatic - Prevention: Triggered when inject is processed',
      TYPE_ARTICLE: 'Article',
      TYPE_CHALLENGE: 'Challenge',
      TYPE_DETECTION: 'Detection',
      TYPE_MANUAL: 'Manual',
      TYPE_PREVENTION: 'Prevention',
      TYPE_HUMAN_RESPONSE: 'Human response',
      FAILED: 'Failed',
      VALIDATED: 'Validated',
      'Ip Address': 'Ip Address',
      'Ip Address {index}': 'Ip Address {index}',
      phone_number_tooltip: 'Phone number should start with a plus sign ( + )\n'
        + 'It may contain white spaces or hyphens ( – ) or parenthesis.\n',
      Exercise: 'Simulation',
      Scheduling_time: 'Time',
      // -- FILTERS --
      // Endpoint
      endpoint_hostname: 'Hostname',
      endpoint_ips: 'IP addresses',
      endpoint_platform: 'Platform',
      endpoint_arch: 'Architecture',
      endpoint_agent_version: 'Agent version',
      recurrence_The: 'The',
      recurrence_at: 'at',
      recurrence_from: 'from',
      recurrence_to: 'to',
      recurrence_starting_from: 'starting from',
      recurrence_Last: 'Last',
      'global-crisis': 'Global Crisis',
      'attack-scenario': 'Attack Scenario',
      'media-pressure': 'Media Pressure',
      'data-exfiltration': 'Data Exfiltration',
      'capture-the-flag': 'Capture The Flag',
      'vulnerability-exploitation': 'Vulnerability Exploitation',
      'lateral-movement': 'Lateral Movement',
      'url-filtering': 'URL Filtering',
      'endpoint-protection': 'Endpoint Protection',
      'web-filtering': 'Web Filtering',
      'incident-response': 'Incident Response',
      'standard-operating-procedure': 'Standard Operating Procedures',
      'crisis-communication': 'Crisis Communication',
      'strategic-reaction': 'Strategic Reaction',
      COMMUNITY: 'Community',
      FILIGRAN: 'Filigran',
      VERIFIED: 'Verified',
      UNVERIFIED: 'Unverified',
      // - XLS Mapper
      Expectation_name: 'Expectation name',
      Expectation_description: 'Expectation description',
      Expectation_score: 'Expectation score',
      Trigger_time: 'Trigger time',
      ABSOLUTE_TIME_WITHOUT_START_DATE: 'Your import contains injects triggered only with the time of the day (e.g.: 9:30) but there is no launch date specified for this scenario. Please specify a launch date for this scenario.',
      // Bulk actions
      'Do you want to delete these {count} injects?': 'Do you want to delete these {count} injects?',
    },
  },
};

export default i18n;
