package io.openbas.jsonapi;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks one or more fields as the "business identifier" of an entity.
 *
 * <p>Unlike the technical primary key (e.g., {@code @Id}), which is usually generated by the
 * database, fields annotated with {@code @BusinessId} represent natural or functional keys that
 * uniquely identify the entity from a business perspective.
 *
 * <p>Multiple fields can be annotated within the same entity class. In such cases, the combination
 * of these fields is considered as a composite business identifier.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface BusinessId {}
