package io.openbas.jsonapi;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field as the "business identifier" of an entity.
 *
 * <p>Unlike the technical primary key (e.g., {@code @Id}), which is usually generated by the
 * database, a field annotated with {@code @BusinessId} represents a natural or functional key that
 * uniquely identifies the entity from a business perspective.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface BusinessId {}
