name: "Test GitHub Actions scripts"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/actions/**'
  push:
    branches: [ main ]
    paths:
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  test-github-actions-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Run tests
        run: node --test .github/actions/**/*.test.js

