name: Deploy feature branch on staging
on:
  workflow_dispatch:
    inputs:
      openaev_config:
        type: string
        default: '{ "SPRING_PROFILES_ACTIVE": "ci,test-feature-branch", "OPENAEV_ENABLED-DEV-FEATURES": "*" }'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  openaev-platform:
    name: openaev-platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.23
          extra-repositories: |
            https://dl-cdn.alpinelinux.org/alpine/edge/community/
          packages: >
            nodejs npm git tini gcc g++ make musl-dev cargo openjdk21-jdk maven postfix postfix-pcre
      - name: Setup Node.js
        run: |
          npm install -g corepack
        shell: alpine.sh --root {0}
      - name: Build into Alpine
        run: |
          export JAVA_HOME=/usr/lib/jvm/default-jvm/
          cd openaev-front
          yarn install
          yarn build
          cd ../
          mvn install -DskipTests -Pdev
        shell: alpine.sh {0}
      - run: mkdir -p openaev-build/
      - run: cp openaev-api/target/openaev-api.jar openaev-build/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: filigran/openaev-platform
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: buildpush
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile_ga_deprecated
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=filigran/openaev-platform:buildcache
          cache-to: type=registry,ref=filigran/openaev-platform:buildcache,mode=max
    outputs:
      dockerBuildDigest: ${{ steps.buildpush.outputs.digest }}
  deploy:
    name: deploy
    needs: [openaev-platform]
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: filigran/openaev-platform
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Install AWX cli
        run: pip install awxkit
      - name: Deploy feature environment via AWX
        run: |
          awx --conf.host ${{ secrets.AWX_URL }} \
            --conf.username ${{ secrets.AWX_USER }} \
            --conf.password ${{ secrets.AWX_PASSWORD }} \
            -f human \
          job_templates launch 'Deploy OpenAEV feature branch for testing' \
            --wait \
            --inventory eu-west-staging \
            --extra_vars '{"openaev_version":"${{steps.meta.outputs.version}}","openaev_config":${{ inputs.openaev_config }},"image_digest":"${{ needs.openaev-platform.outputs.dockerBuildDigest }}"}'
      - name: Forge URL to match playbook limitations
        id: urlforge
        run: |
          url=$(echo "${{steps.meta.outputs.version}}" | cut -c 1-15 | sed 's/[_.]/-/g' | sed 's/-*$//')
          echo "url=$url" >> $GITHUB_OUTPUT
      - name: display URL
        run: echo "https://feat-${{steps.urlforge.outputs.url}}.oaev.staging.filigran.io"
